//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Admin.cpp
//  @ Date : 15.05.2026
//  @ Author : 
//
//


#include "Admin.h"

void Admin::dodajMaterial(string tytul) {

}

Admin::Admin(string l, string h) {

}

Admin::~Admin() {

}

