//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Admin.cpp
//  @ Date : 16.05.2026
//  @ Author :
//
//


#include "Admin.h"

void Admin::dodajZweryfkikowanyMaterial() {

}

Admin::Admin(string l, string h) : Konto(l, h) {

}

Admin::~Admin() {

}

bool Admin::getAktywneDodanie() {

}

void Admin::setAktywneDodanie(bool b) {

}

