//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Admin.cpp
//  @ Date : 21.05.2026
//  @ Author :
//
//


#include "Admin.h"

Admin::Admin(string l, string h) : Konto(l, h) {
    licznikMaterialowDoDodania = 0;
}

Admin::~Admin() {

}

int Admin::getLicznikMaterialowDoDodania() {
    return licznikMaterialowDoDodania;
}

void Admin::setLicznikMaterialowDoDodania(int i) {
    licznikMaterialowDoDodania = i;
}

void Admin::witaj() {

}

