//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Admin.h
//  @ Date : 16.05.2026
//  @ Author : 
//
//


#if !defined(_ADMIN_H)
#define _ADMIN_H

#include "Konto.h"

class Admin : public Konto {
public:
	void dodajZweryfkikowanyMaterial(string tytul);
	Admin(string l, string h);
	~Admin();
};

#endif  //_ADMIN_H
