//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Admin.h
//  @ Date : 16.05.2026
//  @ Author :
//
//


#if !defined(_ADMIN_H)
#define _ADMIN_H

#include "Konto.h"

class Admin : public Konto {
public:
	void dodajZweryfkikowanyMaterial();
	Admin(string l, string h);
	~Admin();
	bool getAktywneDodanie();
	void setAktywneDodanie(bool b);
private:
    bool aktywneDodanie;
};

#endif  //_ADMIN_H
