//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Admin.h
//  @ Date : 21.05.2026
//  @ Author :
//
//


#if !defined(_ADMIN_H)
#define _ADMIN_H

#include "Konto.h"

class Admin : public Konto {
public:
	Admin(string l, string h);
	~Admin();
	int getLicznikMaterialowDoDodania();
	void setLicznikMaterialowDoDodania(int i);
	void witaj();
private:
	int licznikMaterialowDoDodania;
};

#endif  //_ADMIN_H
