//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Konto.h
//  @ Date : 16.05.2026
//  @ Author :
//
//


#if !defined(_KONTO_H)
#define _KONTO_H

#include <string>
#include <iostream>

using namespace std;


class Konto {
public:
	bool autentykacja(string haslo);
	string getLogin();
	string getHaslo();
	void setLogin(string l);
	void setHaslo(string h);
	Konto(string l, string h);
	virtual ~Konto();
private:
	string login;
	string haslo;
};

#endif  //_KONTO_H
