//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Konto.cpp
//  @ Date : 16.05.2026
//  @ Author :
//
//


#include "Konto.h"

bool Konto::autentykacja(string haslo) {

}

string Konto::getLogin() {

}

string Konto::getHaslo() {

}

void Konto::setLogin(string l) {

}

void Konto::setHaslo(string h) {

}

Konto::Konto(string l, string h) {

}

Konto::~Konto() {

}

