//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Material.h
//  @ Date : 16.05.2026
//  @ Author :
//
//


#if !defined(_MATERIAL_H)
#define _MATERIAL_H

#include <string>

using namespace std;


class Material {
public:
	Material(string t, string z);
	~Material();
	string getTytul();
	string getZalacznik();
	void setTytul(string s);
	void setZalacznik(string s);
private:
	string tytul;
	string zalacznik;
};

#endif  //_MATERIAL_H
