//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Material.cpp
//  @ Date : 16.05.2026
//  @ Author :
//
//


#include "Material.h"

Material::Material(string t, string z, bool matOd) {

}

Material::~Material() {

}

string Material::getTytul() {

}

string Material::getZalacznik() {

}

void Material::setTytul(string s) {

}

void Material::setZalacznik(string s) {

}

bool Material::getMaterialOdWykladowcy() {

}

void Material::setMaterialOdWykladowcy(bool b) {

}



