//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Przedmiot.h
//  @ Date : 15.05.2026
//  @ Author : 
//
//


#if !defined(_PRZEDMIOT_H)
#define _PRZEDMIOT_H


class Przedmiot {
public:
	Przedmiot(string n);
	~Przedmiot();
	void attachMaterial(Material* m);
	void detachMaterial(string tytulVal);
	string getNazwa();
	void setNazwa(string s);
	void attachWykladowca(Wykladowca* w);
	void detachWykladowca(string l);
	string getOpis();
	string getKontakt();
	void setOpis(string o);
	void setKontakt(string l);
	void attachStudent(Student* s);
	void detachStudent(string l);
	void znajdzMaterial(string tytul);
private:
	string nazwa;
	vector<Material*> materialy;
	vector<Wykladowca*> wykladowcy;
	string opis;
	string kontakt;
	vector<Student*> studenty;
};

#endif  //_PRZEDMIOT_H
