//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Przedmiot.cpp
//  @ Date : 21.05.2026
//  @ Author :
//
//


#include "Przedmiot.h"

Przedmiot::Przedmiot(string n, string o, string k, string g) {
    nazwa = n;
    opis = o;
    kontakt = k;
    grupa = g;
    cout << "Utworzono przedmiot o nazwie " << getNazwa() << "\n";
}

Przedmiot::~Przedmiot() {
    cout << "Zniszczono przedmiot o nazwie " << getNazwa() << "\n";
}

void Przedmiot::attachMaterial(Material* m) {
    materialy.push_back(m);
}

void Przedmiot::detachMaterial(string tytulVal) {
    vector<Material*>::iterator it;

    Material* foundMaterial = nullptr;

    for (it = materialy.begin(); it != materialy.end(); it++) {
        if ((*it)->getTytul() == tytulVal) {
            foundMaterial = (*it);
            materialy.erase(it);
            break;
        }
    }

    if (foundMaterial == nullptr) {
        cout << "Material o tytule " << tytulVal << " nie znaleziono w systemie\n";
    }
}

string Przedmiot::getNazwa() {
    return nazwa;
}

void Przedmiot::setNazwa(string s) {
    nazwa = s;
}

void Przedmiot::attachWykladowca(Wykladowca* w) {
    wykladowcy.push_back(w);
}

void Przedmiot::detachWykladowca(string l) {
     vector<Wykladowca*>::iterator it;

    Wykladowca* foundWykladowca = nullptr;

    for (it = wykladowcy.begin(); it != wykladowcy.end(); it++) {
        if ((*it)->getLogin() == l) {
            foundWykladowca = (*it);
            wykladowcy.erase(it);
            break;
        }
    }

    if (foundWykladowca == nullptr) {
        cout << "Wykladowcy o loginie " << l << " nie znaleziono w systemie\n";
    }
}

string Przedmiot::getOpis() {
    return opis;
}

string Przedmiot::getKontakt() {
    return kontakt;
}

void Przedmiot::setOpis(string o) {
    opis = o;
}

void Przedmiot::setKontakt(string l) {
    kontakt = l;
}

void Przedmiot::attachStudent(Student* s) {
    studenci.push_back(s);
}

void Przedmiot::detachStudent(string l) {
    vector<Student*>::iterator it;

    Student* foundStudent = nullptr;

    for (it = studenci.begin(); it != studenci.end(); it++) {
        if ((*it)->getLogin() == l) {
            foundStudent = (*it);
            studenci.erase(it);
            break;
        }
    }

    if (foundStudent == nullptr) {
        cout << "Studenta o loginie " << l << " nie znaleziono w systemie\n";
    }
}

Material* Przedmiot::znajdzMaterial(string tytul) {
    vector<Material*>::iterator it;

    for (it = materialy.begin(); it != materialy.end(); it++) {
        if ((*it)->getTytul() == tytul) {
            return *it;
        }
    }

    return nullptr;
}

string Przedmiot::getGrupa() {
    return grupa;
}

void Przedmiot::setGrupa(string g) {
    grupa = g;
}

void Przedmiot::pozyskajMaterial(string n, string tytul, string materialOd, string gr) {

}

void Przedmiot::zaproponujMaterial(string tytul, string zalacznik, string login) {
    if (getStudent(login) == nullptr){
        cout << "Nie mozesz proponowac materialu do przedmiotu, do ktorego nie jestes przypisany, sprobuj ponownie\n";
    }

    Material* materialToAdd = new Material(tytul, zalacznik, false);
    attachMaterial(materialToAdd);
    materialToAdd->setCzyJestZweryfikowany(false);
    materialToAdd->setCzyJestDodanyPrzezAdmina(false);

    vector<Wykladowca*>::iterator it;

    for (it = wykladowcy.begin(); it != wykladowcy.end(); it++){
        (*it)->setLicznikMaterialowDoWeryfikacji((*it)->getLicznikMaterialowDoWeryfikacji() + 1);
    }



    cout << "Sugestia materialu zostala wyslana, prosze poczekac az wykladowca ja sprawdzi\n";
    return;
}

void Przedmiot::dodajMaterial(string t, string z, string login) {
    if (getWykladowca(login) == nullptr){
        cout << "Nie prowadzisz przedmiotu " << nazwa << " , prosze sprobowac ponownie\n";
        return;
    }


    while (t.size() > 64){
        cout << "Tytul materialu nie moze przekraczac 64 znaki\n";
        cin >> ws;
        getline(cin, t);
    }



    string ending = "";

    for (int i = z.size() - 1; i >= 0; i--){
        if (z[i] == '.'){
            ending = ending + z[i];
            break;
        }
        ending = ending + z[i];
    }

    string normalEnding = "";

    for (int i = ending.size() - 1; i >= 0; i--){
        if (ending[i] != ' '){
            normalEnding = normalEnding + ending[i];
        }
    }

    while (normalEnding != ".pdf" && normalEnding != ".DOC" && normalEnding != ".tex" && normalEnding != ".cpp" && normalEnding != ".py" && normalEnding != ".java" && normalEnding != ".csv"
        && normalEnding != ".xlsx" && normalEnding != ".c"){
            cout << "Format " << normalEnding << " nie jest obslugiwany, prosze wpisac nowy zalacznik\n";
            cin >> ws;
            getline(cin, z);

            for (int i = z.size() - 1; i >= 0; i--){
                if (z[i] == '.'){
                    ending = ending + z[i];
                    break;
                }
                ending = ending + z[i];
            }

            string normalEnding = "";

            for (int i = ending.size() - 1; i >= 0; i--){
            if (ending[i] != ' '){
                normalEnding = normalEnding + ending[i];
            }
        }

    }

    Material* materialToAdd = new Material(t, z, true);

    materialToAdd->setCzyJestZweryfikowany(true);
    materialToAdd->setCzyJestDodanyPrzezAdmina(true);

    attachMaterial(materialToAdd);
}

Student* Przedmiot::getStudent(string login) {
    vector<Student*>::iterator it;

    Student* studentFound = nullptr;

    for (it = studenci.begin(); it != studenci.end(); it++){
        if ((*it)->getLogin() == login){
            studentFound = (*it);

            break;
        }
    }

    return studentFound;
}

Wykladowca* Przedmiot::getWykladowca(string login) {
    vector<Wykladowca*>::iterator it;

    Wykladowca* wykladowcaFound = nullptr;

    for (it = wykladowcy.begin(); it != wykladowcy.end(); it++){
        if ((*it)->getLogin() == login){
            wykladowcaFound = (*it);

            break;
        }
    }

    return wykladowcaFound;
}

int Przedmiot::getIloscMaterialow(){
    int size = materialy.size();

    return size;
}

Material* Przedmiot::getMaterial(int i){
    return materialy[i];
}

