//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Przedmiot.cpp
//  @ Date : 15.05.2026
//  @ Author : 
//
//


#include "Przedmiot.h"

Przedmiot::Przedmiot(string n) {

}

Przedmiot::~Przedmiot() {

}

void Przedmiot::attachMaterial(Material* m) {

}

void Przedmiot::detachMaterial(string tytulVal) {

}

string Przedmiot::getNazwa() {

}

void Przedmiot::setNazwa(string s) {

}

void Przedmiot::attachWykladowca(Wykladowca* w) {

}

void Przedmiot::detachWykladowca(string l) {

}

string Przedmiot::getOpis() {

}

string Przedmiot::getKontakt() {

}

void Przedmiot::setOpis(string o) {

}

void Przedmiot::setKontakt(string l) {

}

void Przedmiot::attachStudent(Student* s) {

}

void Przedmiot::detachStudent(string l) {

}

void Przedmiot::znajdzMaterial(string tytul) {

}

