//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Przedmiot.h
//  @ Date : 16.05.2026
//  @ Author :
//
//


#if !defined(_PRZEDMIOT_H)
#define _PRZEDMIOT_H

#include <string>
#include <vector>
#include "Material.h"
#include "Wykladowca.h"
#include "Student.h"

using namespace std;


class Przedmiot {
public:
	Przedmiot(string n, string o, string k);
	~Przedmiot();
	void attachMaterial(Material* m);
	void detachMaterial(string tytulVal);
	string getNazwa();
	void setNazwa(string s);
	void attachWykladowca(Wykladowca* w);
	void detachWykladowca(string l);
	string getOpis();
	string getKontakt();
	void setOpis(string o);
	void setKontakt(string l);
	void attachStudent(Student* s);
	void detachStudent(string l);
	Material* znajdzMaterial(string tytul);
private:
	string nazwa;
	vector<Material*> materialy;
	vector<Wykladowca*> wykladowcy;
	string opis;
	string kontakt;
	vector<Student*> studenty;
};

#endif  //_PRZEDMIOT_H
