//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Przedmiot.h
//  @ Date : 21.05.2026
//  @ Author :
//
//


#if !defined(_PRZEDMIOT_H)
#define _PRZEDMIOT_H

#include "Material.h"
#include "Wykladowca.h"
#include "Student.h"
#include <string>
#include <vector>
#include <iostream>

using namespace std;


class Przedmiot {
public:
	Przedmiot(string n, string o, string k, string g);
	~Przedmiot();
	void attachMaterial(Material* m);
	void detachMaterial(string tytulVal);
	string getNazwa();
	void setNazwa(string s);
	void attachWykladowca(Wykladowca* w);
	void detachWykladowca(string l);
	string getOpis();
	string getKontakt();
	void setOpis(string o);
	void setKontakt(string l);
	void attachStudent(Student* s);
	void detachStudent(string l);
	Material* znajdzMaterial(string tytul);
	string getGrupa();
	void setGrupa(string g);
	void pozyskajMaterial(string n, string tytul, string materialOd, string gr);
	bool zaproponujMaterial(string dane);
	void dodajMaterial(string n, string t, string z);
	Student* getStudent(string login);
	Wykladowca* getWykladowca(string login);
	int getIloscMaterialow();
	Material* getMaterial(int i);
private:
	string nazwa;
	vector<Material*> materialy;
	vector<Wykladowca*> wykladowcy;
	string opis;
	string kontakt;
	vector<Student*> studenci;
	string grupa;
};

#endif  //_PRZEDMIOT_H
