//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Przedmiot.cpp
//  @ Date : 16.05.2026
//  @ Author :
//
//


#include "Przedmiot.h"

Przedmiot::Przedmiot(string n, string o, string k, string g) {

}

Przedmiot::~Przedmiot() {

}

void Przedmiot::attachMaterial(Material* m) {

}

void Przedmiot::detachMaterial(string tytulVal) {

}

string Przedmiot::getNazwa() {

}

void Przedmiot::setNazwa(string s) {

}

void Przedmiot::attachWykladowca(Wykladowca* w) {

}

void Przedmiot::detachWykladowca(string l) {

}

string Przedmiot::getOpis() {

}

string Przedmiot::getKontakt() {

}

void Przedmiot::setOpis(string o) {

}

void Przedmiot::setKontakt(string l) {

}

void Przedmiot::attachStudent(Student* s) {

}

void Przedmiot::detachStudent(string l) {

}

Material* Przedmiot::znajdzMaterial(string tytul) {

}

string Przedmiot::getGrupa() {

}

void Przedmiot::setGrupa(string g) {

}


Material* Przedmiot::getMaterialDoWeryfikacji(string t){

}

Material* Przedmiot::getMaterialDoDodania(string t){

}

void Przedmiot::attachMaterialDoWeryfikacji(Material* m) {

}

void Przedmiot::detachMaterialDoWeryfikacji(string t) {

}

void Przedmiot::attachMaterialDoDodania(Material* m) {

}

void Przedmiot::detachMaterialDoDodania(string t) {

}


