//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Sesja.h
//  @ Date : 15.05.2026
//  @ Author : 
//
//


#if !defined(_SESJA_H)
#define _SESJA_H


class Sesja {
public:
	Sesja(string i);
	~Sesja();
	string getIpAdres();
	int getProby();
	bool getCzyJestZablokowana();
	time_t getZablokowanaDo();
	Konto* getKonto();
	void setIpAdres(string i);
	void setProby(int p);
	void setCzyJestZablokowana(bool b);
	void setZablokowanaDo(time_t t);
	void setKonto(Konto* k);
private:
	string ipAdres;
	int proby;
	bool czyJestZablokowana();
	time_t zablokowanaDo();
	Konto* konto;
};

#endif  //_SESJA_H
