//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Sesja.cpp
//  @ Date : 16.05.2026
//  @ Author : 
//
//


#include "Sesja.h"

Sesja::Sesja(string i) {

}

Sesja::~Sesja() {

}

string Sesja::getIpAdres() {

}

int Sesja::getProby() {

}

bool Sesja::getCzyJestZablokowana() {

}

time_t Sesja::getZablokowanaDo() {

}

Konto* Sesja::getKonto() {

}

void Sesja::setIpAdres(string i) {

}

void Sesja::setProby(int p) {

}

void Sesja::setCzyJestZablokowana(bool b) {

}

void Sesja::setZablokowanaDo(time_t t) {

}

void Sesja::setKonto(Konto* k) {

}

