//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Sesja.h
//  @ Date : 21.05.2026
//  @ Author :
//
//


#if !defined(_SESJA_H)
#define _SESJA_H

#include "Konto.h"
#include <string>
#include <iostream>

using namespace std;


class Sesja {
public:
	Sesja(string i);
	~Sesja();
	string getIpAdres();
	int getProby();
	bool getCzyJestZablokowana();
	time_t getZablokowanaDo();
	void setIpAdres(string i);
	void setProby(int p);
	void setCzyJestZablokowana(bool b);
	void setZablokowanaDo(time_t t);
	time_t getOstatniaProba();
	void setOstatniaProba(time_t t);
private:
	string ipAdres;
	int proby;
	bool czyJestZablokowana;
	time_t zablokowanaDo;
	time_t ostatniaProba;
};

#endif  //_SESJA_H
