//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : StronaInternetowa.cpp
//  @ Date : 21.05.2026
//  @ Author :
//
//


#include "StronaInternetowa.h"
#include <fstream>
#include <sstream>
#include <ctime>
#include <typeinfo>

void StronaInternetowa::attachKonto(Konto* k) {
    konta.push_back(k);
}

void StronaInternetowa::attachSesja(Sesja* s) {
    sesje.push_back(s);
}

void StronaInternetowa::detachKonto(string login) {
    vector<Konto*>::iterator it;

    Konto* foundKonto = nullptr;

    for (it = konta.begin(); it != konta.end(); it++){
        if ((*it)->getLogin() == login){
            foundKonto = (*it);
            konta.erase(it);
            break;
        }
    }

    if (foundKonto == nullptr){
        cout << "Konta o loginie " << login << " nie znaleziono w systemie\n";
    }
}

void StronaInternetowa::detachSesja(string ip) {
    vector<Sesja*>::iterator it;

    Sesja* foundSesja = nullptr;

    for (it = sesje.begin(); it != sesje.end(); it++){
        if ((*it)->getIpAdres() == ip){
            foundSesja = (*it);
            sesje.erase(it);
            break;
        }
    }

    if (foundSesja == nullptr){
        cout << "Sesje o ip " << ip << " nie znaleziono w systemie\n";
    }
}

string StronaInternetowa::getAdres() {
    return adres;
}

string StronaInternetowa::getNazwa() {
    return nazwa;
}

void StronaInternetowa::setNazwa(string n) {
    nazwa = n;
}

void StronaInternetowa::setAdres(string a) {
    adres = a;
}

bool StronaInternetowa::logowanie(string l, string h, string ip) {
    Sesja* currentSession = getSesja(ip);

    if (currentSession == nullptr){
        cout << "Nie znalieziono sesji o ip " << ip << ", proces logowania przerwano\n";
        return false;
    }

    if (currentSession->getCzyJestZablokowana()) {
        time_t currentTime = time(nullptr);

        if (currentTime < currentSession->getZablokowanaDo()) {
            long long left = currentSession->getZablokowanaDo() - currentTime;
            cout << "Sesja zablokowana, " << left << " sekund kary\n";
            return false;
        }
        else {
            currentSession->setCzyJestZablokowana(false);
            currentSession->setProby(0);
            cout << "Blokada minela, mozesz sprobowac ponownie\n";
        }
    }

    Konto* foundKonto = getKonto(l); // changed here

    if (foundKonto == nullptr){
        string userRegisterInput = "";

        cout << "Nie znaleziono uzytkownika o loginie " << l << " , czy chcesz zarejestrowac uzytkownika o takim loginie? (tak / nie)\n";
        cin >> userRegisterInput;

        if (userRegisterInput == "tak"){
            string registerLogin = "";
            string registerPassword = "";

            cout << "Wprowadz login do rejestracji:\n";
            cin >> registerLogin;
            cout << "Wprowadz haslo do rejestracji:\n";
            cin >> registerPassword;

            rejestracja(registerLogin, registerPassword, ip);
        }
        else if (userRegisterInput == "nie"){
            cout << "Anulowanie rejestracji... powrot do logowania ";
            return false;
        }
        else {
            cout << "Nieprawdilowy input, sprobuj ponownie\n";
            return false;
        }

        return false;
    }

    if (foundKonto->autentykacja(h)){
        cout << "Zalogowanie na strone " << adres << " udalo sie\n";
        return true;
    }
    else {
        if (currentSession->getProby() >= 5){
            cout << "Przekroczony limit prob, musimy zablokowac sesje o ip " << currentSession->getIpAdres() << " na 15 minut, prosze sprobowac pozniej\n";

            currentSession->setCzyJestZablokowana(true);
            currentSession->setZablokowanaDo(time(nullptr) + 15 * 60);
        }

        currentSession->setProby(currentSession->getProby() + 1);

        if (5 + 1 - currentSession->getProby() != 0){
            cout << "Niepoprawne haslo dla uzytkownika o loginie " << l << ", sprobuj ponownie, zostalo " << 5 + 1 - currentSession->getProby() << " prob\n";
        }

        return false;
    }
}

bool StronaInternetowa::rejestracja(string l, string h, string ip) {
     Sesja* currentSession = getSesja(ip);

    if (currentSession == nullptr){
        cout << "Nie znalieziono sesji o ip " << ip << ", proces logowania przerwano\n";
        return false;
    }

    Konto* foundKonto = nullptr;
    vector<Konto*>::iterator it;

    if (sprawdzCzyUzytkownikIstnieje(l)){
        cout << "Niestety uzytkownik o loginie " << l << " juz istnieje w systemie, prosze wymyslec sobie inney login uzytkownika\n";

        return false;
    }

    string input = "";
    cout << "Konto jakiego typu chcesz stwrozyc: student, administrator, wykladowca?:\n";

    cin >> input;

    while (input != "student" && input != "administrator" && input != "wykladowca"){
        cout << "Nieprawidlowy input, prosze sprobowac ponownie\n";

        cin >> input;
    }

    string passwordCheck = "";
    cout << "Prosze podtwierdzic haslo:\n";
    cin >> passwordCheck;

    if (passwordCheck == h){
        cout << "Rejestracja udana, dodajemy uzytkownika o loginie " << l << " do systemu...\n";

        Konto* toAdd = nullptr;

        if (input == "student"){
            string grupa = "";
            cout << "Wprowadz swoja grupe\n";

            cin >> grupa;

            toAdd = new Student(l, h, grupa);
        }
        else if (input == "administrator"){
            toAdd = new Admin(l, h);
            dynamic_cast<Admin*> (toAdd)->setLicznikMaterialowDoDodania(0);
        }
        else if (input == "wykladowca"){
            toAdd = new Wykladowca(l, h);
            dynamic_cast<Wykladowca*> (toAdd)->setLicznikMaterialowDoWeryfikacji(0);
        }

        attachKonto(toAdd);

        cout << "Prosze teraz zalogowac sie do systemu\n";
        return true;
    }
    else {
        cout << "Podtwierdzone haslo niestety nie zgadza sie z poprzednim haslem, prosze sprobowac ponownie\n";
        return false;
    }

    return false;
}

void StronaInternetowa::wykonajAkcjeUzytkownika(string login) {
    Konto* foundKonto = getKonto(login);

    if (foundKonto == nullptr){
        cout << "Konta o loginie " << login << " nie ma w systemie, sprobuj ponownie\n";
        return;
    }

    if (typeid(*foundKonto) == typeid(Student)){
        Student* student = dynamic_cast<Student*> (foundKonto);

        string input = "";
        cout << "Czy chcesz dodac material do rewizji albo pozyskac material? (Wpisz dodac lub pozyskac ponizej:)\n";

        cin >> input;

        while (input != "dodac" && input != "pozyskac"){
            cout << "Nieprawidlowy input, prosze sprobowac ponownie\n";

            cin >> input;
        }

        if (input == "dodac"){
            string studentInput = ""; //comeback
            //cout << "Wprowadz przedmiot, do ktorego chcesz dodac material:\n";

            wyswietlPrzypisanePrzedmioty(login);

            string subjectInput = "";

            cout << "Wprowadz nazwe przedmiotu do ktorego chcesz zaproponowac material:\n";
            cin >> ws;
            getline(cin, subjectInput);

            Przedmiot* subjectFound = getPrzedmiot(subjectInput);

            if (subjectFound == nullptr){
                cout << "Przedmiotu o nazwie " << subjectInput << " nie znaleziono w systemie, prosze sprobowac ponownie\n";
                return;
            }

            string title = "";
            string attachment = "";

            cout << "Wprowadz tytul materialu, ktory chcesz zaproponowac:\n";
            cin >> ws;
            getline(cin, title);

            cout << "Wklej zalacznik materialu, ktory chcesz zaproponowac:\n";
            cin >> ws;
            getline(cin, attachment);

            subjectFound->zaproponujMaterial(title, attachment, login);
            zapiszDaneDoPliku("konta.csv", "przedmioty.csv");
        }
        else {
            wyswietlPrzypisanePrzedmioty(login);


            string studentInput = "";
            string materialMadeBy = "";

            cout << "Od kogo chcesz pozyksac material? (wykladowca = od wykladowcow, student = od studentow)\n";

            cin >> materialMadeBy;

            while (materialMadeBy != "wykladowca" && materialMadeBy != "student"){
                cout << "Nieprawidlowy input, sprobuj ponownie\n";
                cin >> materialMadeBy;
            }

            string name = "";
            cout << "Prosze wprowadzic nazwe przedmiotu:\n";
            cin >> name;

            Przedmiot* przedmiotFound = getPrzedmiot(name);

            while (przedmiotFound == nullptr){
                cout << "Przedmiotu " << name << " nie znalieziono w systmie, sprobuj ponownie\n";

                cin >> name;

                przedmiotFound = getPrzedmiot(name);
            }

            if (przedmiotFound->getGrupa() != student->getGrupa()){
                cout << "Nie jestes przypisany do grupy " << przedmiotFound->getGrupa() << " przedmiotu " << przedmiotFound->getNazwa() << "\n";
                return;
            }

            string title = "";
            cout << "Prosze wprowadzic tytul materialu:\n";
            cin >> title;

            Material* material = przedmiotFound->znajdzMaterial(title);

            while (material == nullptr) {
                cout << "Nie znaleziono materialu o tytulu " << title << " dla przedmiotu " << przedmiotFound->getNazwa() << " , sprobuj wprowadzic inny tytul materialu\n";

                cin >> title;
                material = przedmiotFound->znajdzMaterial(title);
            }

            if (materialMadeBy == "student") {
                if (!material->getMaterialOdWykladowcy()){
                    cout << "Zalacznik do pobrania meterialu przygotowanego przez studentow:\n";
                    cout << material->getZalacznik();
                }
                else {
                    cout << "Material o tytulu " << material->getTytul() << " nie byl przygotowany przez studentow, sprobuj sprawdzic materialy od prowadzacych\n";
                    return;
                }
            }
            else {
                if (material->getMaterialOdWykladowcy()){
                    cout << "Zalacznik do pobrania meterialu przygotowanego przez wykladowcow:\n";
                    cout << material->getZalacznik();
                }
                else {
                    cout << "Material o tytulu " << material->getTytul() << " nie byl przygotowany przez wykladowcow, sprobuj sprawdzic materialy od studentow\n";
                    return;
                }
            }
        }
    }
    else if (typeid(*foundKonto) == typeid(Wykladowca)){
        Wykladowca* teacher = dynamic_cast<Wykladowca*>(foundKonto);

        string teacherInput = "";

        if (teacher->getLicznikMaterialowDoWeryfikacji() != 0){
            cout << "Uwaga! W tej chwili masz aktywna sugestie studenta do sprawdzenia. Wprowadz \"sprawdz\", jesli chcesz sprawdzic natychmiastowo, lub nacsinij enter (lub wpisz cokolwiek) jesli chcesz to zrobic pozniej\n";

            cin >> teacherInput;

            if (teacherInput == "sprawdz"){
                zweryfikujSugestieStudenta(foundKonto->getLogin());
                zapiszDaneDoPliku("konta.csv", "przedmioty.csv");
            }
        }

            cout << "Czy chcesz sprawdzic sugestie studenta (jesli teraz jest aktywna w systemie), dodac material lub dodac przedmiot? (sprawdzic = sprawdzic sugestie, material = dodac material, przedmiot = dodac przedmiot do systemu)\n";

            cin >> teacherInput;

            while (teacherInput != "sprawdzic" && teacherInput != "material" && teacherInput != "przedmiot"){
                cout << "Nieprawidlowy input, sprobuj ponownie\n";

                cin >> teacherInput;
            }

            if (teacherInput == "sprawdzic"){
                zweryfikujSugestieStudenta(foundKonto->getLogin());
            }
            else if (teacherInput == "material"){
                wyswietlProwadzonePrzedmioty(login);

                string subjectInput = "";

                cout << "Wybierz przedmiot z listy, zeby dodac do niego material:\n";

                cin >> ws;
                getline(cin, subjectInput);

                cout << "Prosze wpisac tytul materialowi:\n";
                string title = "";
                cin >> ws;
                getline(cin, title);

                cout << "Prosze dodac zalacznik:\n";
                string attachment = "";
                cin >> ws;
                getline(cin, attachment);

                Przedmiot* subjectFound = getPrzedmiot(subjectInput);

                if (subjectFound != nullptr){
                    subjectFound->dodajMaterial(title, attachment, login);

                    zapiszDaneDoPliku("konta.csv", "przedmioty.csv");
                }
                else {
                    cout << "Nie znaleziono przedmiotu " << subjectInput << " w systemie, sprobuj ponownie\n";
                }
            }
            else if (teacherInput == "przedmiot"){
                dodajPrzedmiot(login);

                zapiszDaneDoPliku("konta.csv", "przedmioty.csv");
            }
    }
    else if (typeid(*foundKonto) == typeid(Admin)){
        Admin* admin = dynamic_cast<Admin*> (foundKonto);

        if (admin->getLicznikMaterialowDoDodania() != 0){
            cout << "Masz teraz material do dodania, przystap do pracy w wolnej chwili\n";

            dodajZweryfkikowanyMaterial(foundKonto->getLogin());
        }
    }
}

void StronaInternetowa::attachPrzedmiot(Przedmiot* p) {
    przedmioty.push_back(p);
}

void StronaInternetowa::detachPrzedmiot(string n) {
    vector<Przedmiot*>::iterator it;

    Przedmiot* foundPrzedmiot = nullptr;

    for (it = przedmioty.begin(); it != przedmioty.end(); it++){
        if ((*it)->getNazwa() == n){
            foundPrzedmiot = (*it);

            przedmioty.erase(it);
            break;
        }
    }

    if (foundPrzedmiot == nullptr){
        cout << "Nie znaleziono przedmiotu " << n << " w systemie\n";
    }
}

Przedmiot* StronaInternetowa::getPrzedmiot(string n) {
     vector<Przedmiot*>::iterator it;

    Przedmiot* foundPrzedmiot = nullptr;

    for (it = przedmioty.begin(); it != przedmioty.end(); it++){
        if ((*it)->getNazwa() == n){
            foundPrzedmiot = (*it);
            break;
        }
    }

    return foundPrzedmiot;
}

bool StronaInternetowa::sprawdzCzyUzytkownikIstnieje(string l) {
    vector<Konto*>::iterator it;

    for (it = konta.begin(); it != konta.end(); it++){
        if ((*it)->getLogin() == l){
            return true;
        }
    }

    return false;
}

Konto* StronaInternetowa::getKonto(string l) {
    vector<Konto*>::iterator it;

    Konto* foundKonto = nullptr;

    for (it = konta.begin(); it != konta.end(); it++){
        if ((*it)->getLogin() == l){
            foundKonto = (*it);
            break;
        }
    }

    return foundKonto;
}

Sesja* StronaInternetowa::getSesja(string i) {
    vector<Sesja*>::iterator it;

    Sesja* foundSesja = nullptr;

    for (it = sesje.begin(); it != sesje.end(); it++){
        if ((*it)->getIpAdres() == i){
            foundSesja = (*it);
            break;
        }
    }

    if (foundSesja == nullptr){
        cout << "Sesji o adresie ip " << i << " nie znaleziono w systemie\n";
    }

    return foundSesja;
}

StronaInternetowa::StronaInternetowa(string a, string n) {
    adres = a;
    nazwa = n;
}

StronaInternetowa::~StronaInternetowa() {
    cout << "Strona internetowa " << nazwa << " o adresie " << adres << " zostala zniszczona\n";
}

void StronaInternetowa::dodajZweryfkikowanyMaterial(string login) {

}

void StronaInternetowa::zweryfikujSugestieStudenta(string login) {
    Wykladowca* teacherFound = dynamic_cast<Wykladowca*> (getKonto(login));

    if (teacherFound->getLicznikMaterialowDoWeryfikacji() != 0){
        vector<Przedmiot*>::iterator it;

        for (it = przedmioty.begin(); it != przedmioty.end(); it++){
            if ((*it)->getWykladowca(login) != nullptr){  // wykladowca nalezy do przedmiotu
                int materialSize = (*it)->getIloscMaterialow();

                for (int i = materialSize - 1; i >= 0; i--){
                    Material* currentMaterial = (*it)->getMaterial(i);

                    if (currentMaterial->getCzyJestZweryfikowany() == false && currentMaterial->getCzyJestDodanyPrzezAdmina() == false){
                        string first = "";
                        string second = "";
                        string third = "";


                        cout << "Material " << currentMaterial->getTytul() << " oczekuje na weryfikacje\n";
                        cout << "Zalacznik do materialu : "<< currentMaterial->getZalacznik() << " , prosze pobrac material i ocenic go wedlug ponizszych kryteriow:\n";

                        cout << "Kryterium 1: czy material jest zgodny z tematem? (tak / nie):\n";

                        cin >> first;

                        while (first != "tak" && first != "nie"){
                            cout << "Nieprawidlowy input, sprobuj ponownie\n";
                            cin >> first;
                        }

                        cout << "Kryterium 2: czy material ma charakter edukacyjny?: (tak / nie)\n";

                        cin >> second;

                        while (second != "tak" && second != "nie"){
                            cout << "Nieprawidlowy input, sprobuj ponownie\n";
                            cin >> second;
                        }

                        cout << "Kryterium 3: czy material spelnia standardy akademickie? (tak / nie)\n";

                        cin >> third;

                        while (third != "tak" && third != "nie"){
                            cout << "Nieprawidlowy input, sprobuj ponownie\n";
                            cin >> third;
                        }

                        if (first == "tak" && second == "tak" && third == "tak"){
                            currentMaterial->setCzyJestZweryfikowany(true);

                            Admin* admin = getAdmin();
                            admin->setLicznikMaterialowDoDodania(admin->getLicznikMaterialowDoDodania() + 1);;

                            vector<Konto*>::iterator kIt;

                            for (kIt = konta.begin(); kIt != konta.end(); kIt++){
                                if (typeid(**kIt) == typeid(Wykladowca)){
                                    Wykladowca* currentTeacher = dynamic_cast<Wykladowca*> (*kIt);

                                    if ((*it)->getWykladowca(currentTeacher->getLogin()) != nullptr){
                                        if (currentTeacher->getLicznikMaterialowDoWeryfikacji() > 0){
                                            currentTeacher->setLicznikMaterialowDoWeryfikacji(currentTeacher->getLicznikMaterialowDoWeryfikacji() - 1);
                                        }
                                    }
                                }
                            }
                            cout << "Material o tytule " << currentMaterial->getTytul() << " zostal zweryfikowany\n";
                        }
                        else {
                            cout << "Sugestia zostala odrzucona, nie wszystkie kryteria sa spelnione. Proces usuniecia z systemu...\n";

                            (*it)->detachMaterial(currentMaterial->getTytul());

                            delete currentMaterial;
                        }

                    }
                }

            }
        }


    }

    else {
        cout << "Nie masz w tej chwili materialow do weryfikacji, sproboj pozniej\n";
    }
}

void StronaInternetowa::dodajPrzedmiot(string login) {
    string subjectName = "";
    string subjectDescription = "";
    string subjectContact = "";
    string subjectGroup = "";

    bool nameExists = true;

        while(nameExists){
        bool found = false;
        cout << "Prosze wpisac nazwe przedmiotu:\n";
        cin >> ws;
        getline(cin, subjectName);

        vector<Przedmiot*>::iterator it;

        for (it = przedmioty.begin(); it != przedmioty.end(); it++){
            if ((*it)->getNazwa() == subjectName){
                found = true;
            }
        }

        if (!found){
            nameExists = false;
        }
    }

    cout << "Prosze wpisac kontakt do koordynatora przedmiotu:\n";
    cin >> subjectContact;


    bool descriptionIsTooLong = true;

    while (descriptionIsTooLong){
        cout << "Prosze wpisac opis przedmiotu:\n";
        cin >> ws;
        getline(cin, subjectDescription);

        if (subjectDescription.size() > 256){
            cout << "Opis przedmiotu nie moze przekraczac 256 znakow\n";
        }
        else {
            descriptionIsTooLong = false;
        }
    }

    cout << "Prosze wpisac grupe przypisana do przedmiotu\n";
    cin >> subjectGroup;

    Przedmiot* subjectToAdd = new Przedmiot(subjectName, subjectDescription, subjectContact, subjectGroup);

    string teacherInput = "";

    cout << "Czy chcesz dodac wiecej wykladowcow do nowego przedmiotu " << subjectToAdd->getNazwa() << "? (tak / nie)\n";
    cin >> teacherInput;

    while (teacherInput != "tak" && teacherInput != "nie"){
        cout << "Nieprawdilowy input, prosze sprobowac ponownie\n";
        cin >> teacherInput;
    }

    vector<Wykladowca*> teachersAdded;

    Wykladowca* firstTeacher = dynamic_cast<Wykladowca*> (getKonto(login));
    teachersAdded.push_back(firstTeacher);

    while (teacherInput == "tak"){
        string newTeacherLogin = "";

        cout << "Prosze wpisac login wykladowcy\n";
        cin >> newTeacherLogin;

        Wykladowca* teacherFound = dynamic_cast<Wykladowca*> (getKonto(newTeacherLogin));

        while (teacherFound == nullptr){
            cout << "Wykladowca nie istnieje w systemie\n";
            cout << "Prosze wpisac login wykladowcy\n";

            cin >> newTeacherLogin;

            teacherFound = dynamic_cast<Wykladowca*> (getKonto(newTeacherLogin));
        }

        bool alreadyAdded = true;

        while(alreadyAdded){
            vector<Wykladowca*>::iterator wIt;
            bool found = false;

            for (wIt = teachersAdded.begin(); wIt != teachersAdded.end(); wIt++){
                if ((*wIt)->getLogin() == teacherFound->getLogin()){
                    found = true;
                }
            }

            if (!found){
                break;
            }

            cout << "Wykladowca o loginie " << teacherFound->getLogin() << " juz jest przypisany do przedmiotu\n";

            cout << "Prosze wpisac login wykladowcy\n";
            cin >> newTeacherLogin;

            teacherFound = dynamic_cast<Wykladowca*> (getKonto(newTeacherLogin));

            while (teacherFound == nullptr){
            cout << "Wykladowca nie istnieje w systemie\n";
            cout << "Prosze wpisac login wykladowcy\n";

            cin >> newTeacherLogin;

            teacherFound = dynamic_cast<Wykladowca*> (getKonto(newTeacherLogin));
            }
        }

        teachersAdded.push_back(teacherFound);

        cout << "Czy chcesz dodac wiecej wykladowcow do nowego przedmiotu " << subjectToAdd->getNazwa() << "? (tak / nie)\n";
        cin >> teacherInput;
    }

    vector<Wykladowca*>::iterator wIt;

    for (wIt = teachersAdded.begin(); wIt != teachersAdded.end(); wIt++){
        subjectToAdd->attachWykladowca((*wIt));
    }

    vector<Konto*>::iterator it;

    for (it = konta.begin(); it != konta.end(); it++){
        if (typeid(**it) == typeid(Student)){
            if (dynamic_cast<Student*>(*it)->getGrupa() == subjectToAdd->getGrupa()){
                subjectToAdd->attachStudent(dynamic_cast<Student*>(*it));
            }
        }
    }

    attachPrzedmiot(subjectToAdd);

    cout << "Przedmiot " << subjectToAdd->getNazwa() << " zostal pomyslnie dodany do systemu\n";
    //zapiszDaneDoPliku("konta.csv", "przedmioty.csv");
}

void StronaInternetowa::wyswietlPrzypisanePrzedmioty(string loginl) {
        cout << "Przedmioty, do ktorych jestes przypisany:\n";

        bool atLeastOne = false;
        vector<Przedmiot*>::iterator it;

        for (it = przedmioty.begin(); it != przedmioty.end(); it++){
            Student* currentStudent = (*it)->getStudent(loginl);

            if (currentStudent != nullptr){
                atLeastOne = true;

                cout << (*it)->getNazwa() << " ";
            }
        }

        if (!atLeastOne){
            cout << "Niestety nie jestes przypisany pod zadny przedmiot w tej chwili, prosze sprobowac ponownie\n";
            return;
        }

        cout << "\n";
}

void StronaInternetowa::wyswietlProwadzonePrzedmioty(string login) {
        cout << "Przedmioty, ktore prowadzisz:\n";

        bool atLeastOne = false;
        vector<Przedmiot*>::iterator it;

        for (it = przedmioty.begin(); it != przedmioty.end(); it++){
            Wykladowca* currentTeacher = (*it)->getWykladowca(login);
            int subjectCounter = 0;

            if (currentTeacher != nullptr){
                atLeastOne = true;

                cout << (*it)->getNazwa() << " ";
                }
            }
            cout << "\n";

            if (!atLeastOne){
                cout << "Nie prowadzisz w tej chwili zednego przedmiotu\n";

                return;
            }
}

Admin* StronaInternetowa::getAdmin() {
    vector<Konto*>::iterator it;

    Admin* admin = nullptr;

    for (it = konta.begin(); it != konta.end(); it++){
        if (typeid(**it) == typeid(Admin)){
            admin = dynamic_cast<Admin*> ((*it));
        }
    }

    return admin;
}

void StronaInternetowa::wczytajDaneZPliku(string nazwaPliku, string nazwaPlikuPrzemiotow) {
    ifstream file;

    file.open(nazwaPliku, ios::in);

    string line = "";
    string word = "";

    while (getline(file, line)){
        stringstream s(line);
        int counter = 0;

        string accountType = "";
        string loginFromCsv = "";
        string passwordFromCsv = "";
        string lastColumn = "";

        while (getline(s, word, ',')){
            counter++;
            if (counter == 1){
                accountType = word;
            }

            else if (counter == 2){
                loginFromCsv = word;
            }

            else if (counter == 3){
                passwordFromCsv = word;
            }

            else if (counter == 4){
                lastColumn = word;
            }
        }
            if (accountType == "Student"){
                Student* studentToAdd = new Student(loginFromCsv, passwordFromCsv, lastColumn);

                attachKonto(studentToAdd);
            }
            else if (accountType == "Wykladowca"){
                Wykladowca* teacherToAdd = new Wykladowca(loginFromCsv, passwordFromCsv);

                teacherToAdd->setLicznikMaterialowDoWeryfikacji(stoi(lastColumn));
                attachKonto(teacherToAdd);
            }
            else if (accountType == "Admin"){
                Admin* adminToAdd = new Admin(loginFromCsv, passwordFromCsv);

                adminToAdd->setLicznikMaterialowDoDodania(stoi(lastColumn));
                attachKonto(adminToAdd);
            }

        }
        file.close();

        ifstream subjectFile;

        subjectFile.open(nazwaPlikuPrzemiotow, ios::in);

        vector<string> subjectRow;
        string subjectLine = "";
        string subjectWord = "";


    while (getline(subjectFile, subjectLine)){
        stringstream sSubjet(subjectLine);

        string subjectName = "";
        string subjectDescription = "";
        string subjectContact = "";
        string subjectGroup = "";

        vector<Wykladowca*> teachersToAdd;
        string currentName = "";

        vector<Student*> studentsToAdd;
        string currentStuddentName = "";

        vector<Material*> materialsToAdd;

        string teacherString = "";
        string studentString = "";

        bool teachersStarted = false;
        bool studentsStarted = false;
        bool materialsStarted = false;

        string materialTitle = "";
        string materialAttachment = "";
        bool isByTeacher = false;
        bool isVerified = false;
        bool isAddedByAdmin = false;


        int subjectCounter = 0;
        int materialCounter = 0;

        while(getline(sSubjet, subjectWord, ',')){
            subjectCounter++;

            if (subjectCounter == 1){
                subjectName = subjectWord;
            }
            else if (subjectCounter == 2){
                subjectDescription = subjectWord;
            }
            else if (subjectCounter == 3){
                subjectContact = subjectWord;
            }
            else if (subjectCounter == 4){
                subjectGroup = subjectWord;
            }
            else {
                if (subjectWord == "WYKLADOWCY"){
                    teachersStarted = true;
                    studentsStarted = false;
                    materialsStarted = false;
                    continue;
                }

                if (subjectWord == "STUDENCI"){
                    teachersStarted = false;
                    studentsStarted = true;
                    materialsStarted = false;
                    continue;
                }

                if (subjectWord == "MATERIALY"){
                    teachersStarted = false;
                    studentsStarted = false;
                    materialsStarted = true;
                    continue;
                }

                if (teachersStarted && subjectWord != "brak"){
                    teacherString = subjectWord;

                    Wykladowca* teacherToAdd = dynamic_cast<Wykladowca*> (getKonto(teacherString));
                    if (teacherToAdd != nullptr){
                        teachersToAdd.push_back(teacherToAdd);
                    }
                }

                else if (studentsStarted && subjectWord != "brak"){
                    studentString = subjectWord;

                    Student* studentToAdd = dynamic_cast<Student*> (getKonto(studentString));
                    if (studentToAdd != nullptr){
                        studentsToAdd.push_back(studentToAdd);
                    }
                }

                else if (materialsStarted && subjectWord != "brak"){
                    materialCounter++;

                    if (materialCounter == 1){
                        materialTitle = subjectWord;
                    }
                    else if (materialCounter == 2){
                        materialAttachment = subjectWord;
                    }
                    else if (materialCounter == 3){
                        if (subjectWord == "true"){
                            isByTeacher = true;
                        }
                        else {
                            isByTeacher = false;
                        }
                    }
                    else if (materialCounter == 4){
                        if (subjectWord == "true"){
                            isVerified = true;
                        }
                        else {
                            isVerified = false;
                        }
                    }
                    else if (materialCounter == 5){
                        if (subjectWord == "true"){
                            isAddedByAdmin = true;
                        }
                        else{
                            isAddedByAdmin = false;
                        }

                        Material* materialToAdd = new Material(materialTitle, materialAttachment, isByTeacher);
                        materialToAdd->setCzyJestZweryfikowany(isVerified);
                        materialToAdd->setCzyJestDodanyPrzezAdmina(isAddedByAdmin);;

                        materialsToAdd.push_back(materialToAdd);

                        materialCounter = 0;
                    }
                }
            }
        }


    Przedmiot* subjectToAdd = new Przedmiot(subjectName, subjectDescription, subjectContact, subjectGroup);

    vector<Wykladowca*>::iterator wIt;

    for (wIt = teachersToAdd.begin(); wIt != teachersToAdd.end(); wIt++){
        subjectToAdd->attachWykladowca((*wIt));
    }

    vector<Student*>::iterator sIt;

    for (sIt = studentsToAdd.begin(); sIt != studentsToAdd.end(); sIt++){
        subjectToAdd->attachStudent((*sIt));
    }

    vector<Material*>::iterator mIt;

    for (mIt = materialsToAdd.begin(); mIt != materialsToAdd.end(); mIt++){
        subjectToAdd->attachMaterial((*mIt));
    }

    attachPrzedmiot(subjectToAdd);

    }

    subjectFile.close();
}


void StronaInternetowa::zapiszDaneDoPliku(string nazwaPliku, string nazwaPlikuPrzedmiotow) {
    vector<Konto*>::iterator it;

    ofstream accountFile(nazwaPliku);

    if (!accountFile.is_open()){
        cout << "Nie otwiera sie plik z kontami\n";
        return;
    }

    for (it = konta.begin(); it != konta.end(); it++){
        string accountType = "";
        string accountLogin = "";
        string accountPassword = "";
        string studentGroup = "";
        string teacherAmountOfMaterialsToVerify = "";
        string adminAmountOfMaterialsToAdd = "";


        if (typeid(**it) == typeid(Student)){
            accountType = "Student";

            accountLogin = (*it)->getLogin();

            accountPassword = (*it)->getHaslo();
            studentGroup = dynamic_cast<Student*> (*it)->getGrupa();

            accountFile << accountType << "," << accountLogin << "," << accountPassword << "," << studentGroup;
            accountFile << "\n";
        }
        else if (typeid(**it) == typeid(Wykladowca)){
            accountType = "Wykladowca";
            accountLogin = (*it)->getLogin();
            accountPassword = (*it)->getHaslo();
            teacherAmountOfMaterialsToVerify = to_string(dynamic_cast<Wykladowca*> (*it)->getLicznikMaterialowDoWeryfikacji());

            accountFile << accountType << "," << accountLogin << "," << accountPassword << "," << teacherAmountOfMaterialsToVerify;
            accountFile << "\n";
        }
        else if (typeid(**it) == typeid(Admin)){
            accountType = "Admin";
            accountLogin = (*it)->getLogin();
            accountPassword = (*it)->getHaslo();
            adminAmountOfMaterialsToAdd = to_string(dynamic_cast<Admin*> (*it)->getLicznikMaterialowDoDodania());

            accountFile << accountType << "," << accountLogin << "," << accountPassword << "," << adminAmountOfMaterialsToAdd;
            accountFile << "\n";
        }
    }

    accountFile.close();

    ofstream subjectFile(nazwaPlikuPrzedmiotow);

    if (!subjectFile.is_open()){
        cout << "Nie otwiera sie plik z przedmiotami\n";
        return;
    }

    vector<Przedmiot*>::iterator pIt;

    for (pIt = przedmioty.begin(); pIt != przedmioty.end(); pIt++){
        string subjectName = "";
        string subjectDescription = "";
        string subjectContact = "";
        string subjectGroup = "";

        subjectName = (*pIt)->getNazwa();
        subjectDescription = (*pIt)->getOpis();
        subjectContact = (*pIt)->getKontakt();
        subjectGroup = (*pIt)->getGrupa();

        subjectFile << subjectName << "," << subjectDescription << "," << subjectContact << "," << subjectGroup;
        subjectFile << ",WYKLADOWCY";

        vector<Konto*>::iterator accIterator;

        for (accIterator = konta.begin(); accIterator != konta.end(); accIterator++){
            if (typeid(**accIterator) == typeid(Wykladowca)){
                if ((*pIt)->getWykladowca((*accIterator)->getLogin()) != nullptr){
                    subjectFile << "," << ((*accIterator)->getLogin());
                }
            }
        }

        subjectFile << ",STUDENCI";

        bool hasStudents = false;

        for (accIterator = konta.begin(); accIterator != konta.end(); accIterator++){
            if (typeid(**accIterator) == typeid(Student)){
                if ((*pIt)->getStudent((*accIterator)->getLogin()) != nullptr){
                    subjectFile << "," << ((*accIterator)->getLogin());
                    hasStudents = true;
                }
            }
        }

        if (!hasStudents){
            subjectFile << ",brak";
        }

        subjectFile << ",MATERIALY";

        int materialSize = (*pIt)->getIloscMaterialow();

        if (materialSize == 0){
            subjectFile << ",brak";
        }
            else {
            for (int i = 0; i < materialSize; i++){
                string currentTitle = "";
                string currentAttachment = "";
                string fromTeacher = "";
                string isVerified = "";
                string isAddedByAdmin = "";

                Material* currentMaterial = (*pIt)->getMaterial(i);

                if (currentMaterial != nullptr){
                    subjectFile << "," << currentMaterial->getTytul() << "," << currentMaterial->getZalacznik();

                    if (currentMaterial->getMaterialOdWykladowcy()){
                        fromTeacher = "true";
                    }
                    else{
                        fromTeacher = "false";
                    }

                    if (currentMaterial->getCzyJestZweryfikowany()){
                        isVerified = "true";
                    }
                    else {
                        isVerified = "false";
                    }

                    if (currentMaterial->getCzyJestDodanyPrzezAdmina()){
                        isAddedByAdmin = "true";
                    }
                    else {
                        isAddedByAdmin = "false";
                    }

                    subjectFile << "," << fromTeacher << "," << isVerified << "," << isAddedByAdmin;

                }
            }
        }
        subjectFile << "\n";
    }
}

void StronaInternetowa::debugPrintAllUsers(){
    vector<Konto*>::iterator it;

    for (it = konta.begin(); it != konta.end(); it++){
        if (typeid(**it) == typeid(Admin)){
            cout << "admin amount : " << dynamic_cast<Admin*>(*it)->getLicznikMaterialowDoDodania();
        }

        cout << (*it)->getLogin() << " ";
    }

    cout << "przedmioty:\n";

    vector<Przedmiot*>::iterator itT;

    for (itT = przedmioty.begin(); itT != przedmioty.end(); itT++){
        cout << (*itT)->getNazwa() << " ";
    }

    cout << "\n";

}

