//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : StronaInternetowa.h
//  @ Date : 16.05.2026
//  @ Author :
//
//


#if !defined(_STRONAINTERNETOWA_H)
#define _STRONAINTERNETOWA_H

#include "Konto.h"
#include "Sesja.h"
#include "Przedmiot.h"


class StronaInternetowa {
public:
	void attachKonto(Konto* k);
	void attachSesja(Sesja* s);
	void detachKonto(string login);
	void detachSesja(string ip);
	string getAdres();
	string getNazwa();
	void setNazwa(string n);
	void setAdres(string a);
	bool logowanie(string l, string h, string ip);
	bool rejestracja(string l, string h, string ip);
	void wykonajAkcjeUzytkownika();
	void attachPrzedmiot(Przedmiot* p);
	void detachPrzedmiot(string n);
	Przedmiot* getPrzedmiot(string n);
	bool sprawdzCzyUzytkownikIstnieje(Konto* k);
	StronaInternetowa(string a, string n);
	~StronaInternetowa();
private:
	string adres;
	string nazwa;
	vector<Konto*> konta;
	vector<Sesja*> sesje;
	vector<Przedmiot*> przedmioty;
};

#endif  //_STRONAINTERNETOWA_H
