//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.h
//  @ Date : 16.05.2026
//  @ Author :
//
//


#if !defined(_STUDENT_H)
#define _STUDENT_H

#include "Konto.h"

class Student : public Konto {
public:
	void pozyskajMaterial(string n, string tytul, string g);
	bool zaproponujMaterial(string dane);
	Student(string l, string h, string g);
	~Student();
	string getGrupa();
	void setGrupa(string g);
private:
	string grupa;
};

#endif  //_STUDENT_H
