//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.h
//  @ Date : 15.05.2026
//  @ Author : 
//
//


#if !defined(_STUDENT_H)
#define _STUDENT_H

#include "Konto.h"

class Student : public Konto {
public:
	void pozyskajMaterial(string n, string tytul, string g);
	bool zaproponujMaterial(string dane);
	Student(string l, string h);
	~Student();
private:
	string grupa;
};

#endif  //_STUDENT_H
