//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.cpp
//  @ Date : 21.05.2026
//  @ Author :
//
//


#include "Student.h"

Student::Student(string l, string h, string g) : Konto(l, h) {
    grupa = g;
}

Student::~Student() {
    cout << "Zniszczono konto studenta o loginie " << getLogin() << "\n";
}

string Student::getGrupa() {
    return grupa;
}

void Student::setGrupa(string g) {
    grupa = g;
}

string Student::getIndeksStudenta() {
    return indeksStudenta;
}

void Student::setIndeksStudenta(string i) {
    indeksStudenta = i;
}

void Student::witaj() {
    cout << "Witamy w systemie, studencie " << getLogin() << "\n";
}

