//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.h
//  @ Date : 21.05.2026
//  @ Author :
//
//


#if !defined(_STUDENT_H)
#define _STUDENT_H

#include "Konto.h"

class Student : public Konto {
public:
	Student(string l, string h, string g);
	~Student();
	string getGrupa();
	void setGrupa(string g);
	string getIndeksStudenta();
	void setIndeksStudenta(string i);
	void witaj();
private:
	string grupa;
	string indeksStudenta;
};

#endif  //_STUDENT_H
