//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.cpp
//  @ Date : 15.05.2026
//  @ Author : 
//
//


#include "Student.h"

void Student::pozyskajMaterial(string n, string tytul, string g) {

}

bool Student::zaproponujMaterial(string dane) {

}

Student::Student(string l, string h) {

}

Student::~Student() {

}

