//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.cpp
//  @ Date : 16.05.2026
//  @ Author :
//
//


#include "Student.h"

void Student::pozyskajMaterial(string n, string tytul, string g) {

}

bool Student::zaproponujMaterial(string dane) {

}

Student::Student(string l, string h, string g) : Konto(l, h) {
    grupa = g;
}

Student::~Student() {

}

string Student::getGrupa() {

}

void Student::setGrupa(string g) {

}


