//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SystemEdukacyjny.h
//  @ Date : 21.05.2026
//  @ Author :
//
//


#if !defined(_SYSTEMEDUKACYJNY_H)
#define _SYSTEMEDUKACYJNY_H

#include "Konto.h"
#include "Admin.h"
#include "Sesja.h"
#include "Przedmiot.h"
#include <iostream>

using namespace std;



class SystemEdukacyjny {
public:
	void attachKonto(Konto* k);
	void detachKonto(string login);
	string getNazwa();
	void setNazwa(string n);
	bool logowanie(string l, string h, string plikZIndeksami, string plikZKontami, string plikZPrzedmiotami);
	bool rejestracja(string l, string h, string plikZIndeksami, string plikZKontami, string plikZPrzedmiotami);
	bool wykonajAkcjeUzytkownika(string login, string plikZKontami, string plikZPrzedmiotami);
	void attachPrzedmiot(Przedmiot* p);
	void detachPrzedmiot(string n);
	Przedmiot* getPrzedmiot(string n);
	bool sprawdzCzyUzytkownikIstnieje(string l);
	Konto* getKonto(string l);
	SystemEdukacyjny(string n);
	~SystemEdukacyjny();
	void dodajZweryfkikowanyMaterial(string login);
	void zweryfikujSugestieStudenta(string login);
	void dodajPrzedmiot(string login);
	void wyswietlPrzypisanePrzedmioty(string loginl);
	void wyswietlProwadzonePrzedmioty(string login);
	Admin* getAdmin();
	void wczytajPrzedmiotyIKontaZPliku(string nazwaPliku, string nazwaPlikuPrzedmiotow);
	void zapiszPrzedmiotyIKontaDoPliku(string nazwaPliku, string nazwaPlikuPrzedmiotow);
	bool zweryfikujIndeks(string indeks, string typKonta, string nazwaPliku);
	void zaktualizujIndeks(string indeks, string login, string nazwaPliku);
	void przypiszStudentaDoPrzedmiotuPoGrupie(string login);
	void printDataSesja();
	void setDataSesja(string ip, int proby, bool czyJestZablokowana, time_t zablokowanaDo, time_t ostatniaProba);
	void wczytajSesje(string nazwaPlikuSesji);
	void zapiszSesje(string nazwaPlikuSesji);
	vector<Konto*>& getKonta();
    vector<Przedmiot*>& getPrzedmioty();
private:
	string nazwa;
	vector<Konto*> konta;
	Sesja* aktywnaSesja;
	vector<Przedmiot*> przedmioty;
};

#endif  //_STRONAINTERNETOWA_H
