//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SystemEdukacyjny.cpp
//  @ Date : 21.05.2026
//  @ Author :
//
//


#include "SystemEdukacyjny.h"
#include <fstream>
#include <sstream>
#include <ctime>
#include <typeinfo>

void SystemEdukacyjny::attachKonto(Konto* k) {
    konta.push_back(k);
}

void SystemEdukacyjny::detachKonto(string login) {
    vector<Konto*>::iterator it;

    Konto* foundKonto = nullptr;

    for (it = konta.begin(); it != konta.end(); it++){
        if ((*it)->getLogin() == login){
            foundKonto = (*it);
            konta.erase(it);
            break;
        }
    }

    if (foundKonto == nullptr){
        cout << "Konta o loginie " << login << " nie znaleziono w systemie\n";
    }
}

string SystemEdukacyjny::getNazwa() {
    return nazwa;
}

void SystemEdukacyjny::setNazwa(string n) {
    nazwa = n;
}

bool SystemEdukacyjny::logowanie(string l, string h) {
    wczytajSesje("sesje.csv");

    time_t currentTime = time(nullptr);

    if (!aktywnaSesja->getCzyJestZablokowana() && aktywnaSesja->getProby() > 0){
        if (currentTime - aktywnaSesja->getOstatniaProba() > 1800){
            aktywnaSesja->setProby(0);
            aktywnaSesja->setOstatniaProba(0);
            zapiszSesje("sesje.csv");

            cout << "Poprzednie proby wygasly, minelo ponad pol godziny od czasu ostatniej proby\n";

            zapiszSesje("sesje.csv");
        }
    }


    if (aktywnaSesja->getCzyJestZablokowana()) {
        if (currentTime < aktywnaSesja->getZablokowanaDo()) {
            long long left = aktywnaSesja->getZablokowanaDo() - currentTime;
            cout << "Sesja zablokowana, " << left << " sekund kary\n";
            return false;
        }
        else {
            aktywnaSesja->setCzyJestZablokowana(false);
            aktywnaSesja->setProby(0);
            aktywnaSesja->setOstatniaProba(0);
            cout << "Blokada minela, mozesz sprobowac ponownie\n";
        }
    }

    Konto* foundKonto = getKonto(l);

    if (foundKonto == nullptr){
        string userRegisterInput = "";

        cout << "Nie znaleziono uzytkownika o loginie " << l << " , czy chcesz zarejestrowac uzytkownika o takim loginie? (tak / nie)\n";
        cin >> userRegisterInput;

        if (userRegisterInput == "tak"){
            string registerLogin = "";
            string registerPassword = "";

            cout << "Wprowadz login do rejestracji:\n";
            cin >> registerLogin;
            cout << "Wprowadz haslo do rejestracji:\n";
            cin >> registerPassword;

            rejestracja(registerLogin, registerPassword);
        }
        else if (userRegisterInput == "nie"){
            cout << "Anulowanie rejestracji... powrot do logowania ";
            return false;
        }
        else {
            cout << "Nieprawdilowy input, sprobuj ponownie\n";
            return false;
        }

        return false;
    }

    if (foundKonto->autentykacja(h)){
        cout << "Zalogowanie do systemu " << nazwa << " udalo sie\n";
        aktywnaSesja->setProby(0);
        aktywnaSesja->setOstatniaProba(0);
        zapiszSesje("sesje.csv");

        foundKonto->witaj();
        return true;
    }
    else {
        aktywnaSesja->setProby(aktywnaSesja->getProby() + 1);
        aktywnaSesja->setOstatniaProba(currentTime);

        if (aktywnaSesja->getProby() >= 5){
            cout << "Przekroczony limit prob, musimy zablokowac sesje o ip " << aktywnaSesja->getIpAdres() << " na 15 minut, prosze sprobowac pozniej\n";

            aktywnaSesja->setCzyJestZablokowana(true);
            aktywnaSesja->setZablokowanaDo(time(nullptr) + 15 * 60);
        }
        else {
            cout << "Niepoprawne haslo dla uzytkownika o loginie " << l << ", sprobuj ponownie, zostalo " << 5 - aktywnaSesja->getProby() << " prob\n";
        }

        zapiszSesje("sesje.csv");
        return false;
    }
}

bool SystemEdukacyjny::rejestracja(string l, string h) {
    Konto* foundKonto = nullptr;
    vector<Konto*>::iterator it;

    if (sprawdzCzyUzytkownikIstnieje(l)){
        cout << "Niestety uzytkownik o loginie " << l << " juz istnieje w systemie, prosze wymyslec sobie inney login uzytkownika\n";

        return false;
    }

    string input = "";
    cout << "Konto jakiego typu chcesz stwrozyc: student, wykladowca?:\n";

    cin >> input;

    while (input != "student" && input != "wykladowca"){
        cout << "Nieprawidlowy input, prosze sprobowac ponownie\n";

        cin >> input;
    }

    string passwordCheck = "";
    cout << "Prosze podtwierdzic haslo:\n";
    cin >> passwordCheck;

    if (passwordCheck == h){
    string indexInput = "";

        if (input == "student"){
            cout << "Wprowadz numer indeksu, ktory zostal ci przydzielony przez uczelnie\n";
            cin >> indexInput;

            bool isValid = zweryfikujIndeks(indexInput, "STUDENT", "indeksy.csv");

            if (isValid){
                zaktualizujIndeks(indexInput, l, "indeksy.csv");
                cout << "Przypisujemy twojemu nowemu kontu numer indeksu studenta...";
            }
            else {
                cout << "Niestety wprowadzony numer indeksu " << indexInput << " nie istnieje w systemie, albo jest zajety przez innego studenta\n";
                return false;
            }
        }
        else if (input == "wykladowca") {
            cout << "Wprowadz numer indeksu, ktory zostal ci przydzielony przez uczelnie jako pracownikowi\n";
            cin >> indexInput;

            bool isValid = zweryfikujIndeks(indexInput, "WYKLADOWCA", "indeksy.csv");

            if (isValid){
                zaktualizujIndeks(indexInput, l, "indeksy.csv");
                cout << "Przypisujemy twojemu nowemu kontu numer indeksu wykladowcy...";
            }
            else {
                cout << "Niestety wprowadzony numer indeksu " << indexInput << " nie istnieje w systemie, albo jest zajety przez innego wykladowce\n";
                return false;
            }
        }


        cout << "Rejestracja udana, dodajemy uzytkownika o loginie " << l << " do systemu...\n";

        Konto* toAdd = nullptr;

        if (input == "student"){
            string grupa = "";
            cout << "Wprowadz swoja grupe\n";

            cin >> grupa;

            toAdd = new Student(l, h, grupa, indexInput);
        }
        else if (input == "wykladowca"){
            toAdd = new Wykladowca(l, h, indexInput);
            dynamic_cast<Wykladowca*> (toAdd)->setLicznikMaterialowDoWeryfikacji(0);
        }

        attachKonto(toAdd);

        if (input == "student"){
            przypiszStudentaDoPrzedmiotuPoGrupie(l);
        }

        zapiszPrzedmiotyIKontaDoPliku("konta.csv", "przedmioty.csv");

        cout << "Prosze teraz zalogowac sie do systemu\n";
        return true;
    }
    else {
        cout << "Podtwierdzone haslo niestety nie zgadza sie z poprzednim haslem, prosze sprobowac ponownie\n";
        return false;
    }

    return false;
}

bool SystemEdukacyjny::wykonajAkcjeUzytkownika(string login) {
    Konto* foundKonto = getKonto(login);

    if (foundKonto == nullptr){
        cout << "Konta o loginie " << login << " nie ma w systemie, sprobuj ponownie\n";
        return true;
    }

    if (typeid(*foundKonto) == typeid(Student)){
        Student* student = dynamic_cast<Student*> (foundKonto);

        string input = "";
        cout << "Czy chcesz dodac material do rewizji, pozyskac material lub zakonczyc dzialanie programu?\n";
        cout << "Wpisz jedno z nastepujacych polecen:\n";
        cout << "1)Dodac\n";
        cout << "2)Pozyskac\n";
        cout << "3)Zakoncz dzialanie\n";

        cin >> ws;
        getline(cin, input);

        while (input != "Dodac" && input != "Pozyskac" && input != "Zakoncz dzialanie"){
            cout << "Nieprawidlowy input, prosze sprobowac ponownie\n";

            getline(cin, input);
        }

        if (input == "Zakoncz dzialanie"){
            cout << "Trwa proces zamykania programu...\n";
            return false;
        }

        if (input == "Dodac"){
            string studentInput = "";

            wyswietlPrzypisanePrzedmioty(login);

            string subjectInput = "";

            cout << "Wprowadz nazwe przedmiotu do ktorego chcesz zaproponowac material:\n";
            cin >> ws;
            getline(cin, subjectInput);

            Przedmiot* subjectFound = getPrzedmiot(subjectInput);

            if (subjectFound == nullptr){
                cout << "Przedmiotu o nazwie " << subjectInput << " nie znaleziono w systemie, prosze sprobowac ponownie\n";
                return true;
            }

            string title = "";
            string attachment = "";

            cout << "Wprowadz tytul materialu, ktory chcesz zaproponowac:\n";
            cin >> ws;
            getline(cin, title);

            cout << "Wklej zalacznik materialu, ktory chcesz zaproponowac:\n";
            cin >> ws;
            getline(cin, attachment);

            subjectFound->zaproponujMaterial(title, attachment, login);
            zapiszPrzedmiotyIKontaDoPliku("konta.csv", "przedmioty.csv");
        }
        else {
            wyswietlPrzypisanePrzedmioty(login);

            string subjectInput = "";
            cout << "Wprowadz nazwe przedmiotu z ktorego chcesz pozyskac material:\n";

            cin >> ws;
            getline(cin, subjectInput);

            Przedmiot* subjectFound = getPrzedmiot(subjectInput);

            if (subjectFound == nullptr){
                cout << "Przedmiotu o nazwie " << subjectInput << " nie znaleziono w systemie, prosze sprobowac ponownie\n";

                return true;
            }

            subjectFound->pozyskajMaterial(login);
        }
        return true;
    }
    else if (typeid(*foundKonto) == typeid(Wykladowca)){
        Wykladowca* teacher = dynamic_cast<Wykladowca*>(foundKonto);

        string teacherInput = "";

        if (teacher->getLicznikMaterialowDoWeryfikacji() != 0){
            cout << "Uwaga! W tej chwili masz aktywna sugestie studenta do sprawdzenia\n";
            cout << "Wpisz jedno z nastepujacych polecen:\n";
            cout << "1)Sprawdz\n";
            cout << "2)Potem\n";

            cin >> teacherInput;

            while (teacherInput != "Sprawdz" && teacherInput != "Potem"){
                cout << "Nieprawidlowy input, prosze sprobowac ponownie\n";
                cin >> teacherInput;
            }

            if (teacherInput == "Sprawdz"){
                zweryfikujSugestieStudenta(foundKonto->getLogin());
                zapiszPrzedmiotyIKontaDoPliku("konta.csv", "przedmioty.csv");
            }
        }

            cout << "Czy chcesz sprawdzic sugestie studenta (jesli teraz jest aktywna w systemie), dodac material, dodac przedmiot lub zakonczyc dzialanie?\n";
            cout << "Wpisz jedno z nastepujacych polecen:\n";
            cout << "1)Sprawdz\n";
            cout << "2)Material\n";
            cout << "3)Przedmiot\n";
            cout << "4)Zakoncz dzialanie\n";


            cin >> ws;
            getline(cin, teacherInput);

            while (teacherInput != "Sprawdz" && teacherInput != "Material" && teacherInput != "Przedmiot" && teacherInput != "Zakoncz dzialanie"){
                cout << "Nieprawidlowy input, sprobuj ponownie\n";

                cin >> ws;
                getline(cin, teacherInput);
            }

            if (teacherInput == "Zakoncz dzialanie"){
                cout << "Trwa zamykanie programu...\n";
                return false;
            }

            if (teacherInput == "Sprawdz"){
                zweryfikujSugestieStudenta(foundKonto->getLogin());
                zapiszPrzedmiotyIKontaDoPliku("konta.csv", "przedmioty.csv");
            }
            else if (teacherInput == "Material"){
                wyswietlProwadzonePrzedmioty(login);

                string subjectInput = "";

                cout << "Wybierz przedmiot z listy, zeby dodac do niego material:\n";

                cin >> ws;
                getline(cin, subjectInput);

                Przedmiot* subjectFound = getPrzedmiot(subjectInput);

                if (subjectFound == nullptr){
                    cout << "Nie znaleziono przedmiotu " << subjectInput << " w systemie\n";
                    return true;
                }

                cout << "Prosze wpisac tytul materialowi:\n";
                string title = "";
                cin >> ws;
                getline(cin, title);

                cout << "Prosze dodac zalacznik:\n";
                string attachment = "";
                cin >> ws;
                getline(cin, attachment);

                subjectFound->dodajMaterial(title, attachment, login);
                zapiszPrzedmiotyIKontaDoPliku("konta.csv", "przedmioty.csv");
            }
            else if (teacherInput == "Przedmiot"){
                dodajPrzedmiot(login);

                zapiszPrzedmiotyIKontaDoPliku("konta.csv", "przedmioty.csv");
            }
        return true;
    }
    else if (typeid(*foundKonto) == typeid(Admin)){
        Admin* admin = dynamic_cast<Admin*> (foundKonto);

        if (admin->getLicznikMaterialowDoDodania() != 0){
            cout << "Masz teraz material do dodania, przystap do pracy w wolnej chwili\n";

            dodajZweryfkikowanyMaterial(foundKonto->getLogin());
            zapiszPrzedmiotyIKontaDoPliku("konta.csv", "przedmioty.csv");
            return true;
        }
        else {
            string adminInput = "";
            cout << "Czy chcesz dodac mateiraly zweryfikowane przez wykladowcow, jesli takie istnieja lub zakonczyc dzialanie\n";
            cout << "Wpisz jedno z nastepujacych polecen:\n";
            cout << "1)Dodac\n";
            cout << "2)Zakoncz dzialanie\n";

            cin >> ws;
            getline(cin, adminInput);

            while (adminInput != "Dodac" && adminInput != "Zakoncz dzialanie"){
                cout << "Nieprawidlowy input, prosze sprobowac ponownie\n";

                cin >> ws;
                getline(cin, adminInput);
            }
            if (adminInput == "Zakoncz dzialanie"){
                cout << "Trwa zamykanie programu...\n";
                return false;
            }
            dodajZweryfkikowanyMaterial(login);
            zapiszPrzedmiotyIKontaDoPliku("konta.csv", "przedmioty.csv");
            return true;
        }
    }
    return true;
}

void SystemEdukacyjny::attachPrzedmiot(Przedmiot* p) {
    przedmioty.push_back(p);
}

void SystemEdukacyjny::detachPrzedmiot(string n) {
    vector<Przedmiot*>::iterator it;

    Przedmiot* foundPrzedmiot = nullptr;

    for (it = przedmioty.begin(); it != przedmioty.end(); it++){
        if ((*it)->getNazwa() == n){
            foundPrzedmiot = (*it);

            przedmioty.erase(it);
            break;
        }
    }

    if (foundPrzedmiot == nullptr){
        cout << "Nie znaleziono przedmiotu " << n << " w systemie\n";
    }
}

Przedmiot* SystemEdukacyjny::getPrzedmiot(string n) {
     vector<Przedmiot*>::iterator it;

    Przedmiot* foundPrzedmiot = nullptr;

    for (it = przedmioty.begin(); it != przedmioty.end(); it++){
        if ((*it)->getNazwa() == n){
            foundPrzedmiot = (*it);
            break;
        }
    }

    return foundPrzedmiot;
}

bool SystemEdukacyjny::sprawdzCzyUzytkownikIstnieje(string l) {
    vector<Konto*>::iterator it;

    for (it = konta.begin(); it != konta.end(); it++){
        if ((*it)->getLogin() == l){
            return true;
        }
    }

    return false;
}

Konto* SystemEdukacyjny::getKonto(string l) {
    vector<Konto*>::iterator it;

    Konto* foundKonto = nullptr;

    for (it = konta.begin(); it != konta.end(); it++){
        if ((*it)->getLogin() == l){
            foundKonto = (*it);
            break;
        }
    }

    return foundKonto;
}

SystemEdukacyjny::SystemEdukacyjny(string n) {
    nazwa = n;

    string ipAdres = "127.0.0.1";

    aktywnaSesja = new Sesja(ipAdres);
}

SystemEdukacyjny::~SystemEdukacyjny() {
    cout << "System edukacyjny o nazwie " << nazwa << " zostal zniszczony\n";

    delete aktywnaSesja;
}

void SystemEdukacyjny::dodajZweryfkikowanyMaterial(string login) {
    vector<Przedmiot*>::iterator it;
    Admin* admin = dynamic_cast<Admin*> (getKonto(login));

    if (admin->getLicznikMaterialowDoDodania() != 0){
        for (it = przedmioty.begin(); it != przedmioty.end(); it++){
            int materialSize = (*it)->getIloscMaterialow();

            for (int i = materialSize - 1; i >= 0; i--){
                Material* currentMaterial = (*it)->getMaterial(i);

                if (currentMaterial->getCzyJestZweryfikowany() && !currentMaterial->getCzyJestDodanyPrzezAdmina()){
                    string adminInput = "";
                    cout << "Material o tytule " << currentMaterial->getTytul() << " wpisz tak by dodac zweryfikowany material\n";

                    cin >> adminInput;
                    while (adminInput != "tak"){
                        cout << "Nieprawidlowy input, sprobuj ponownie\n";
                        cin >> adminInput;
                    }
                    currentMaterial->setCzyJestDodanyPrzezAdmina(true);

                    if (admin->getLicznikMaterialowDoDodania() > 0){
                        admin->setLicznikMaterialowDoDodania(admin->getLicznikMaterialowDoDodania() - 1);
                    }

                    cout << "Material o tytule " << currentMaterial->getTytul() << " zostal dodany do systemu. Studenci teraz moga uzyskac dostep do tego materialu\n";
                }
            }
        }
    }
    else {
        cout << "Nie masz w tej chwili zweryfikowanych materialow do dodania, sprobuj pozniej\n";
    }
}

void SystemEdukacyjny::zweryfikujSugestieStudenta(string login) {
    Wykladowca* teacherFound = dynamic_cast<Wykladowca*> (getKonto(login));

    if (teacherFound->getLicznikMaterialowDoWeryfikacji() != 0){
        vector<Przedmiot*>::iterator it;

        for (it = przedmioty.begin(); it != przedmioty.end(); it++){
            if ((*it)->getWykladowca(login) != nullptr){
                int materialSize = (*it)->getIloscMaterialow();

                for (int i = materialSize - 1; i >= 0; i--){
                    Material* currentMaterial = (*it)->getMaterial(i);

                    if (currentMaterial->getCzyJestZweryfikowany() == false && currentMaterial->getCzyJestDodanyPrzezAdmina() == false){
                        string first = "";
                        string second = "";
                        string third = "";


                        cout << "Material " << currentMaterial->getTytul() << " oczekuje na weryfikacje\n";
                        cout << "Zalacznik do materialu : "<< currentMaterial->getZalacznik() << " , prosze pobrac material i ocenic go wedlug ponizszych kryteriow:\n";

                        cout << "Kryterium 1: czy material jest zgodny z tematem?\n";
                        cout << "Wpisz jedno z nastepujacych polecen:\n";
                        cout << "1)Tak\n";
                        cout << "2)Nie\n";

                        cin >> first;

                        while (first != "Tak" && first != "Nie"){
                            cout << "Nieprawidlowy input, sprobuj ponownie\n";
                            cin >> first;
                        }

                        cout << "Kryterium 2: czy material ma charakter edukacyjny?\n";
                        cout << "Wpisz jedno z nastepujacych polecen:\n";
                        cout << "1)Tak\n";
                        cout << "2)Nie\n";

                        cin >> second;

                        while (second != "Tak" && second != "Nie"){
                            cout << "Nieprawidlowy input, sprobuj ponownie\n";
                            cin >> second;
                        }

                        cout << "Kryterium 3: czy material spelnia standardy akademickie?\n";
                        cout << "Wpisz jedno z nastepujacych polecen:\n";
                        cout << "1)Tak\n";
                        cout << "2)Nie\n";

                        cin >> third;

                        while (third != "Tak" && third != "Nie"){
                            cout << "Nieprawidlowy input, sprobuj ponownie\n";
                            cin >> third;
                        }

                        if (first == "Tak" && second == "Tak" && third == "Tak"){
                            currentMaterial->setCzyJestZweryfikowany(true);

                            Admin* admin = getAdmin();
                            admin->setLicznikMaterialowDoDodania(admin->getLicznikMaterialowDoDodania() + 1);;

                            vector<Konto*>::iterator kIt;

                            for (kIt = konta.begin(); kIt != konta.end(); kIt++){
                                if (typeid(**kIt) == typeid(Wykladowca)){
                                    Wykladowca* currentTeacher = dynamic_cast<Wykladowca*> (*kIt);

                                    if ((*it)->getWykladowca(currentTeacher->getLogin()) != nullptr){
                                        if (currentTeacher->getLicznikMaterialowDoWeryfikacji() > 0){
                                            currentTeacher->setLicznikMaterialowDoWeryfikacji(currentTeacher->getLicznikMaterialowDoWeryfikacji() - 1);
                                        }
                                    }
                                }
                            }
                            cout << "Material o tytule " << currentMaterial->getTytul() << " zostal zweryfikowany\n";
                        }
                        else {
                            cout << "Sugestia zostala odrzucona, nie wszystkie kryteria sa spelnione. Proces usuniecia z systemu...\n";

                            (*it)->detachMaterial(currentMaterial->getTytul());

                            delete currentMaterial;
                        }

                    }
                }

            }
        }


    }

    else {
        cout << "Nie masz w tej chwili materialow do weryfikacji, sproboj pozniej\n";
    }
}

void SystemEdukacyjny::dodajPrzedmiot(string login) {
    string subjectName = "";
    string subjectDescription = "";
    string subjectContact = "";
    string subjectGroup = "";

    cout << "Prosze wpisac nazwe przedmiotu:\n";
    cin >> ws;
    getline(cin, subjectName);

        while(true){
        bool found = false;

        vector<Przedmiot*>::iterator it;

        for (it = przedmioty.begin(); it != przedmioty.end(); it++){
            if ((*it)->getNazwa() == subjectName){
                found = true;
            }
        }

        if (!found){
            break;
        }

        cout << "Niepoprawna nazwa: przedmiot o nazwie " << subjectName << " juz istnieje w systemie, wprowadz inna nazwe:\n";
        cin >> ws;
        getline(cin, subjectName);
    }

    cout << "Prosze wpisac kontakt do koordynatora przedmiotu:\n";
    cin >> subjectContact;


    bool descriptionIsTooLong = true;

    while (descriptionIsTooLong){
        cout << "Prosze wpisac opis przedmiotu:\n";
        cin >> ws;
        getline(cin, subjectDescription);

        if (subjectDescription.size() > 256){
            cout << "Opis przedmiotu nie moze przekraczac 256 znakow\n";
        }
        else {
            descriptionIsTooLong = false;
        }
    }

    cout << "Prosze wpisac grupe przypisana do przedmiotu\n";
    cin >> subjectGroup;

    Przedmiot* subjectToAdd = new Przedmiot(subjectName, subjectDescription, subjectContact, subjectGroup);

    string teacherInput = "";

    cout << "Czy chcesz dodac wiecej wykladowcow do nowego przedmiotu " << subjectToAdd->getNazwa() << "\n";
    cout << "Wpisz jedno z nastepujacych polecen:\n";
    cout << "1)Tak\n";
    cout << "2)Nie\n";

    cin >> teacherInput;

    while (teacherInput != "Tak" && teacherInput != "Nie"){
        cout << "Nieprawdilowy input, prosze sprobowac ponownie\n";
        cin >> teacherInput;
    }

    vector<Wykladowca*> teachersAdded;

    Wykladowca* firstTeacher = dynamic_cast<Wykladowca*> (getKonto(login));
    teachersAdded.push_back(firstTeacher);

    while (teacherInput == "Tak"){
        string newTeacherLogin = "";

        cout << "Prosze wpisac login wykladowcy\n";
        cin >> newTeacherLogin;

        Wykladowca* teacherFound = dynamic_cast<Wykladowca*> (getKonto(newTeacherLogin));

        while (teacherFound == nullptr){
            cout << "Wykladowca nie istnieje w systemie\n";
            cout << "Prosze wpisac login wykladowcy\n";

            cin >> newTeacherLogin;

            teacherFound = dynamic_cast<Wykladowca*> (getKonto(newTeacherLogin));
        }

        bool alreadyAdded = true;

        while(alreadyAdded){
            vector<Wykladowca*>::iterator wIt;
            bool found = false;

            for (wIt = teachersAdded.begin(); wIt != teachersAdded.end(); wIt++){
                if ((*wIt)->getLogin() == teacherFound->getLogin()){
                    found = true;
                }
            }

            if (!found){
                break;
            }

            cout << "Wykladowca o loginie " << teacherFound->getLogin() << " juz jest przypisany do przedmiotu\n";

            cout << "Prosze wpisac login wykladowcy\n";
            cin >> newTeacherLogin;

            teacherFound = dynamic_cast<Wykladowca*> (getKonto(newTeacherLogin));

            while (teacherFound == nullptr){
            cout << "Wykladowca nie istnieje w systemie\n";
            cout << "Prosze wpisac login wykladowcy\n";

            cin >> newTeacherLogin;

            teacherFound = dynamic_cast<Wykladowca*> (getKonto(newTeacherLogin));
            }
        }

        teachersAdded.push_back(teacherFound);

        cout << "Czy chcesz dodac wiecej wykladowcow do nowego przedmiotu " << subjectToAdd->getNazwa() << "?\n";
        cout << "Wpisz jedno z nastepujacych polecen:\n";
        cout << "1)Tak\n";
        cout << "2)Nie\n";
        cin >> teacherInput;
    }

    cout << "Wpisz nastepujace polecenie, aby zatwierdzic dodanie przedmiotu:\n";
    cout << "1)Zatwierdz\n";

    string confirmInput = "";
    cin >> confirmInput;

    while (confirmInput != "Zatwierdz"){
        cout << "Nieprawidlowy input, prosze sprobowac ponownie\n";
        cin >> confirmInput;
    }

    vector<Wykladowca*>::iterator wIt;

    for (wIt = teachersAdded.begin(); wIt != teachersAdded.end(); wIt++){
        subjectToAdd->attachWykladowca((*wIt));
    }

    vector<Konto*>::iterator it;

    for (it = konta.begin(); it != konta.end(); it++){
        if (typeid(**it) == typeid(Student)){
            if (dynamic_cast<Student*>(*it)->getGrupa() == subjectToAdd->getGrupa()){
                subjectToAdd->attachStudent(dynamic_cast<Student*>(*it));
            }
        }
    }

    attachPrzedmiot(subjectToAdd);

    cout << "Przedmiot " << subjectToAdd->getNazwa() << " zostal pomyslnie dodany do systemu\n";
}

void SystemEdukacyjny::wyswietlPrzypisanePrzedmioty(string loginl) {
        cout << "Przedmioty, do ktorych jestes przypisany:\n";

        bool atLeastOne = false;
        vector<Przedmiot*>::iterator it;

        for (it = przedmioty.begin(); it != przedmioty.end(); it++){
            Student* currentStudent = (*it)->getStudent(loginl);

            if (currentStudent != nullptr){
                atLeastOne = true;

                cout << (*it)->getNazwa() << " ";
            }
        }

        if (!atLeastOne){
            cout << "Niestety nie jestes przypisany pod zadny przedmiot w tej chwili, prosze sprobowac ponownie\n";
            return;
        }

        cout << "\n";
}

void SystemEdukacyjny::wyswietlProwadzonePrzedmioty(string login) {
        cout << "Przedmioty, ktore prowadzisz:\n";

        bool atLeastOne = false;
        vector<Przedmiot*>::iterator it;

        for (it = przedmioty.begin(); it != przedmioty.end(); it++){
            Wykladowca* currentTeacher = (*it)->getWykladowca(login);
            int subjectCounter = 0;

            if (currentTeacher != nullptr){
                atLeastOne = true;

                cout << (*it)->getNazwa() << " ";
                }
            }
            cout << "\n";

            if (!atLeastOne){
                cout << "Nie prowadzisz w tej chwili zednego przedmiotu\n";

                return;
            }
}

Admin* SystemEdukacyjny::getAdmin() {
    vector<Konto*>::iterator it;

    Admin* admin = nullptr;

    for (it = konta.begin(); it != konta.end(); it++){
        if (typeid(**it) == typeid(Admin)){
            admin = dynamic_cast<Admin*> ((*it));
        }
    }

    return admin;
}

void SystemEdukacyjny::wczytajPrzedmiotyIKontaZPliku(string nazwaPliku, string nazwaPlikuPrzemiotow) {
    ifstream file;

    file.open(nazwaPliku, ios::in);

    string line = "";
    string word = "";

    while (getline(file, line)){
        stringstream s(line);
        int counter = 0;

        string accountType = "";
        string loginFromCsv = "";
        string passwordFromCsv = "";
        string preLastColumn = "";
        string lastColumn = "";

        while (getline(s, word, ',')){
            counter++;
            if (counter == 1){
                accountType = word;
            }

            else if (counter == 2){
                loginFromCsv = word;
            }

            else if (counter == 3){
                passwordFromCsv = word;
            }

            else if (counter == 4){
                preLastColumn = word;
            }
            else if (counter == 5){
                lastColumn = word;
            }
        }
            if (accountType == "Student"){
                Student* studentToAdd = new Student(loginFromCsv, passwordFromCsv, preLastColumn, lastColumn);
                studentToAdd->setIndeksStudenta(lastColumn);

                attachKonto(studentToAdd);
            }
            else if (accountType == "Wykladowca"){
                Wykladowca* teacherToAdd = new Wykladowca(loginFromCsv, passwordFromCsv, lastColumn);
                teacherToAdd->setIndeksWykladowcy(lastColumn);

                teacherToAdd->setLicznikMaterialowDoWeryfikacji(stoi(preLastColumn));
                attachKonto(teacherToAdd);
            }
            else if (accountType == "Admin"){
                Admin* adminToAdd = new Admin(loginFromCsv, passwordFromCsv);

                adminToAdd->setLicznikMaterialowDoDodania(stoi(preLastColumn));
                attachKonto(adminToAdd);
            }

        }
        file.close();

        ifstream subjectFile;

        subjectFile.open(nazwaPlikuPrzemiotow, ios::in);

        vector<string> subjectRow;
        string subjectLine = "";
        string subjectWord = "";


    while (getline(subjectFile, subjectLine)){
        stringstream sSubjet(subjectLine);

        string subjectName = "";
        string subjectDescription = "";
        string subjectContact = "";
        string subjectGroup = "";

        vector<Wykladowca*> teachersToAdd;
        string currentName = "";

        vector<Student*> studentsToAdd;
        string currentStuddentName = "";

        vector<Material*> materialsToAdd;

        string teacherString = "";
        string studentString = "";

        bool teachersStarted = false;
        bool studentsStarted = false;
        bool materialsStarted = false;

        string materialTitle = "";
        string materialAttachment = "";
        bool isByTeacher = false;
        bool isVerified = false;
        bool isAddedByAdmin = false;


        int subjectCounter = 0;
        int materialCounter = 0;

        while(getline(sSubjet, subjectWord, ',')){
            subjectCounter++;

            if (subjectCounter == 1){
                subjectName = subjectWord;
            }
            else if (subjectCounter == 2){
                subjectDescription = subjectWord;
            }
            else if (subjectCounter == 3){
                subjectContact = subjectWord;
            }
            else if (subjectCounter == 4){
                subjectGroup = subjectWord;
            }
            else {
                if (subjectWord == "WYKLADOWCY"){
                    teachersStarted = true;
                    studentsStarted = false;
                    materialsStarted = false;
                    continue;
                }

                if (subjectWord == "STUDENCI"){
                    teachersStarted = false;
                    studentsStarted = true;
                    materialsStarted = false;
                    continue;
                }

                if (subjectWord == "MATERIALY"){
                    teachersStarted = false;
                    studentsStarted = false;
                    materialsStarted = true;
                    continue;
                }

                if (teachersStarted && subjectWord != "brak"){
                    teacherString = subjectWord;

                    Wykladowca* teacherToAdd = dynamic_cast<Wykladowca*> (getKonto(teacherString));
                    if (teacherToAdd != nullptr){
                        teachersToAdd.push_back(teacherToAdd);
                    }
                }

                else if (studentsStarted && subjectWord != "brak"){
                    studentString = subjectWord;

                    Student* studentToAdd = dynamic_cast<Student*> (getKonto(studentString));
                    if (studentToAdd != nullptr){
                        studentsToAdd.push_back(studentToAdd);
                    }
                }

                else if (materialsStarted && subjectWord != "brak"){
                    materialCounter++;

                    if (materialCounter == 1){
                        materialTitle = subjectWord;
                    }
                    else if (materialCounter == 2){
                        materialAttachment = subjectWord;
                    }
                    else if (materialCounter == 3){
                        if (subjectWord == "true"){
                            isByTeacher = true;
                        }
                        else {
                            isByTeacher = false;
                        }
                    }
                    else if (materialCounter == 4){
                        if (subjectWord == "true"){
                            isVerified = true;
                        }
                        else {
                            isVerified = false;
                        }
                    }
                    else if (materialCounter == 5){
                        if (subjectWord == "true"){
                            isAddedByAdmin = true;
                        }
                        else{
                            isAddedByAdmin = false;
                        }

                        Material* materialToAdd = new Material(materialTitle, materialAttachment, isByTeacher);
                        materialToAdd->setCzyJestZweryfikowany(isVerified);
                        materialToAdd->setCzyJestDodanyPrzezAdmina(isAddedByAdmin);;

                        materialsToAdd.push_back(materialToAdd);

                        materialCounter = 0;
                    }
                }
            }
        }


    Przedmiot* subjectToAdd = new Przedmiot(subjectName, subjectDescription, subjectContact, subjectGroup);

    vector<Wykladowca*>::iterator wIt;

    for (wIt = teachersToAdd.begin(); wIt != teachersToAdd.end(); wIt++){
        subjectToAdd->attachWykladowca((*wIt));
    }

    vector<Student*>::iterator sIt;

    for (sIt = studentsToAdd.begin(); sIt != studentsToAdd.end(); sIt++){
        subjectToAdd->attachStudent((*sIt));
    }

    vector<Material*>::iterator mIt;

    for (mIt = materialsToAdd.begin(); mIt != materialsToAdd.end(); mIt++){
        subjectToAdd->attachMaterial((*mIt));
    }

    attachPrzedmiot(subjectToAdd);

    }

    subjectFile.close();
}


void SystemEdukacyjny::zapiszPrzedmiotyIKontaDoPliku(string nazwaPliku, string nazwaPlikuPrzedmiotow) {
    vector<Konto*>::iterator it;

    ofstream accountFile(nazwaPliku);

    if (!accountFile.is_open()){
        cout << "Nie otwiera sie plik z kontami\n";
        return;
    }

    for (it = konta.begin(); it != konta.end(); it++){
        string accountType = "";
        string accountLogin = "";
        string accountPassword = "";
        string studentGroup = "";
        string teacherAmountOfMaterialsToVerify = "";
        string adminAmountOfMaterialsToAdd = "";
        string index = "";


        if (typeid(**it) == typeid(Student)){
            accountType = "Student";

            accountLogin = (*it)->getLogin();

            accountPassword = (*it)->getHaslo();
            studentGroup = dynamic_cast<Student*> (*it)->getGrupa();
            index = dynamic_cast<Student*> (*it)->getIndeksStudenta();

            accountFile << accountType << "," << accountLogin << "," << accountPassword << "," << studentGroup << "," << index;
            accountFile << "\n";
        }
        else if (typeid(**it) == typeid(Wykladowca)){
            accountType = "Wykladowca";
            accountLogin = (*it)->getLogin();
            accountPassword = (*it)->getHaslo();
            teacherAmountOfMaterialsToVerify = to_string(dynamic_cast<Wykladowca*> (*it)->getLicznikMaterialowDoWeryfikacji());
            index = dynamic_cast<Wykladowca*> (*it)->getIndeksWykladowcy();

            accountFile << accountType << "," << accountLogin << "," << accountPassword << "," << teacherAmountOfMaterialsToVerify << "," << index;
            accountFile << "\n";
        }
        else if (typeid(**it) == typeid(Admin)){
            accountType = "Admin";
            accountLogin = (*it)->getLogin();
            accountPassword = (*it)->getHaslo();
            adminAmountOfMaterialsToAdd = to_string(dynamic_cast<Admin*> (*it)->getLicznikMaterialowDoDodania());

            accountFile << accountType << "," << accountLogin << "," << accountPassword << "," << adminAmountOfMaterialsToAdd;
            accountFile << "\n";
        }
    }

    accountFile.close();

    ofstream subjectFile(nazwaPlikuPrzedmiotow);

    if (!subjectFile.is_open()){
        cout << "Nie otwiera sie plik z przedmiotami\n";
        return;
    }

    vector<Przedmiot*>::iterator pIt;

    for (pIt = przedmioty.begin(); pIt != przedmioty.end(); pIt++){
        string subjectName = "";
        string subjectDescription = "";
        string subjectContact = "";
        string subjectGroup = "";

        subjectName = (*pIt)->getNazwa();
        subjectDescription = (*pIt)->getOpis();
        subjectContact = (*pIt)->getKontakt();
        subjectGroup = (*pIt)->getGrupa();

        subjectFile << subjectName << "," << subjectDescription << "," << subjectContact << "," << subjectGroup;
        subjectFile << ",WYKLADOWCY";

        vector<Konto*>::iterator accIterator;

        for (accIterator = konta.begin(); accIterator != konta.end(); accIterator++){
            if (typeid(**accIterator) == typeid(Wykladowca)){
                if ((*pIt)->getWykladowca((*accIterator)->getLogin()) != nullptr){
                    subjectFile << "," << ((*accIterator)->getLogin());
                }
            }
        }

        subjectFile << ",STUDENCI";

        bool hasStudents = false;

        for (accIterator = konta.begin(); accIterator != konta.end(); accIterator++){
            if (typeid(**accIterator) == typeid(Student)){
                if ((*pIt)->getStudent((*accIterator)->getLogin()) != nullptr){
                    subjectFile << "," << ((*accIterator)->getLogin());
                    hasStudents = true;
                }
            }
        }

        if (!hasStudents){
            subjectFile << ",brak";
        }

        subjectFile << ",MATERIALY";

        int materialSize = (*pIt)->getIloscMaterialow();

        if (materialSize == 0){
            subjectFile << ",brak";
        }
            else {
            for (int i = 0; i < materialSize; i++){
                string currentTitle = "";
                string currentAttachment = "";
                string fromTeacher = "";
                string isVerified = "";
                string isAddedByAdmin = "";

                Material* currentMaterial = (*pIt)->getMaterial(i);

                if (currentMaterial != nullptr){
                    subjectFile << "," << currentMaterial->getTytul() << "," << currentMaterial->getZalacznik();

                    if (currentMaterial->getMaterialOdWykladowcy()){
                        fromTeacher = "true";
                    }
                    else{
                        fromTeacher = "false";
                    }

                    if (currentMaterial->getCzyJestZweryfikowany()){
                        isVerified = "true";
                    }
                    else {
                        isVerified = "false";
                    }

                    if (currentMaterial->getCzyJestDodanyPrzezAdmina()){
                        isAddedByAdmin = "true";
                    }
                    else {
                        isAddedByAdmin = "false";
                    }

                    subjectFile << "," << fromTeacher << "," << isVerified << "," << isAddedByAdmin;

                }
            }
        }
        subjectFile << "\n";
    }
}

bool SystemEdukacyjny::zweryfikujIndeks(string indeks, string typKonta, string nazwaPliku) {
    ifstream file;

    file.open(nazwaPliku, ios::in);

    string line = "";
    string word = "";

    while (getline(file, line)){
        stringstream s(line);
        int counter = 0;

        string currentIndex = "";
        string currentAccountType = "";
        string currentLogin = "";

        while(getline(s, word, ',')){
            counter++;

            if (counter == 1){
                currentIndex = word;
            }
            else if (counter == 2){
                currentAccountType = word;
            }
            else if (counter == 3){
                currentLogin = word;
            }
        }

        if (currentAccountType == typKonta && indeks == currentIndex){
            if (currentLogin == "brak"){
                return true;
            }
            else {
                return false;
            }
        }
    }

    file.close();

    return false;
}


void SystemEdukacyjny::zaktualizujIndeks(string indeks, string login, string nazwaPliku) {
    ifstream in;
    in.open(nazwaPliku, ios::in);

    string line = "";
    string word = "";
    string contents = "";

    while (getline(in, line)){
        stringstream s(line);
        int counter = 0;

        string currentIndex = "";
        string currentAccountType = "";
        string currentLogin = "";

        while (getline(s, word, ',')){
            counter++;

            if (counter == 1){
                currentIndex = word;
            }
            else if (counter == 2){
                currentAccountType = word;
            }
            else if (counter == 3){
                currentLogin = word;
            }
        }

        if (currentIndex == indeks){
            currentLogin = login;
        }

        contents = contents + currentIndex + "," + currentAccountType + "," + currentLogin + "\n";
    }

    in.close();

    ofstream out;
    out.open(nazwaPliku, ios::out | ios::trunc);

    out << contents;

    out.close();
}

void SystemEdukacyjny::przypiszStudentaDoPrzedmiotuPoGrupie(string login) {
    Student* foundStudent = dynamic_cast<Student*> (getKonto(login));
    vector<Przedmiot*>::iterator it;

    for (it = przedmioty.begin(); it != przedmioty.end(); it++){
        if ((*it)->getGrupa() == foundStudent->getGrupa()){
            (*it)->attachStudent(foundStudent);
        }
    }

}

void SystemEdukacyjny::printDataSesja() {
    cout << "Aktywna sesja o adresie ip " << aktywnaSesja->getIpAdres() << ": aktywna liczba prob = " << aktywnaSesja->getProby();

    if (aktywnaSesja->getCzyJestZablokowana()){
        cout << ", zablokowana do " << aktywnaSesja->getZablokowanaDo() << "\n";
    }
    else {
        cout <<", nie jest obecnie zablokowana\n";
    }
}

void SystemEdukacyjny::setDataSesja(string ip, int proby, bool czyJestZablokowana, time_t zablokowanaDo, time_t ostatniaProba) {
    aktywnaSesja->setIpAdres(ip);
    aktywnaSesja->setProby(proby);
    aktywnaSesja->setCzyJestZablokowana(czyJestZablokowana);
    aktywnaSesja->setZablokowanaDo(zablokowanaDo);
    aktywnaSesja->setOstatniaProba(ostatniaProba);
}

void SystemEdukacyjny::wczytajSesje(string nazwaPlikuSesji) {
    ifstream file(nazwaPlikuSesji, ios::in);
    if (!file.is_open()){
        return;
    }

    string line, word;
    while(getline(file, line)){
        stringstream s(line);

        string ip = "";
        string attempts = "";
        string isBlocked = "";
        string blokcedTill = "";
        string lastAttempt = "";

        int counter = 0;

        while (getline(s, word, ',')){
            counter++;

            if (counter == 1){
                ip = word;
            }
            else if (counter == 2){
                attempts = word;
            }
            else if (counter == 3){
                isBlocked = word;
            }
            else if (counter == 4){
                blokcedTill = word;
            }
            else if (counter == 5){
                lastAttempt = word;
            }
        }
        if (ip == aktywnaSesja->getIpAdres()){
            bool isBlockedBool = false;

            if (isBlocked == "false"){
                isBlockedBool = false;
            }
            else if (isBlocked == "true"){
                isBlockedBool = true;
            }

            setDataSesja(ip, stoi(attempts), isBlockedBool, stoll(blokcedTill), stoll(lastAttempt));
            break;
        }
    }
    file.close();
}

void SystemEdukacyjny::zapiszSesje(string nazwaPlikuSesji) {
    ifstream in(nazwaPlikuSesji, ios::in);

    string line = "";
    string contents = "";

    if (in.is_open()){
        while (getline(in, line)){
            stringstream s(line);
            string fileIp;
            getline(s, fileIp, ',');

            if (fileIp != aktywnaSesja->getIpAdres() && !fileIp.empty()){
                contents = contents + line + "\n";
            }
        }
        in.close();
    }

    if (aktywnaSesja->getProby() > 0 || aktywnaSesja->getCzyJestZablokowana()){
        string status = "";

        if (aktywnaSesja->getCzyJestZablokowana()){
            status = "true";
        }
        else if (!aktywnaSesja->getCzyJestZablokowana()){
            status = "false";
        }

        contents = contents + aktywnaSesja->getIpAdres() + ',' + to_string(aktywnaSesja->getProby()) + "," + status + "," + to_string(aktywnaSesja->getZablokowanaDo()) + "," + to_string(aktywnaSesja->getOstatniaProba()) + "\n";
    }

    ofstream out(nazwaPlikuSesji, ios::out | ios::trunc);

    if (out.is_open()){
        out << contents;
        out.close();
    }
}

vector<Konto*>& SystemEdukacyjny::getKonta() {
    return konta;
}

vector<Przedmiot*>& SystemEdukacyjny::getPrzedmioty() {
    return przedmioty;
}
