//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wykladowca.cpp
//  @ Date : 21.05.2026
//  @ Author :
//
//


#include "Wykladowca.h"

Wykladowca::Wykladowca(string l, string h) : Konto(l, h) {
    licznikMaterialowDoWeryfikacji = 0;
}

Wykladowca::~Wykladowca() {
    cout << "Zniszczono konto wykladowcy o loginie " << getLogin() << "\n";
}

int Wykladowca::getLicznikMaterialowDoWeryfikacji() {
    return licznikMaterialowDoWeryfikacji;
}

void Wykladowca::setLicznikMaterialowDoWeryfikacji(int i) {
    licznikMaterialowDoWeryfikacji = i;
}

string Wykladowca::getIndeksWykladowcy(){
    return indeksWykladowcy;
}

void Wykladowca::setIndeksWykladowcy(string i) {
    indeksWykladowcy = i;
}

void Wykladowca::witaj() {
    cout << "Witamy w systemie, wykladowco " << getLogin() << "\n";
}

