//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wykladowca.h
//  @ Date : 21.05.2026
//  @ Author :
//
//


#if !defined(_WYKLADOWCA_H)
#define _WYKLADOWCA_H

#include "Konto.h"

class Wykladowca : public Konto {
public:
	Wykladowca(string l, string h);
	~Wykladowca();
	int getLicznikMaterialowDoWeryfikacji();
	void setLicznikMaterialowDoWeryfikacji(int i);
	string getIndeksWykladowcy();
	void setIndeksWykladowcy(string i);
	void witaj();
private:
	int licznikMaterialowDoWeryfikacji;
	string indeksWykladowcy;
};

#endif  //_WYKLADOWCA_H
