//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wykladowca.cpp
//  @ Date : 21.05.2026
//  @ Author :
//
//


#include "Wykladowca.h"

Wykladowca::Wykladowca(string l, string h) : Konto(l, h) {
    licznikMaterialowDoWeryfikacji = 0;
}

Wykladowca::~Wykladowca() {

}

int Wykladowca::getLicznikMaterialowDoWeryfikacji() {
    return licznikMaterialowDoWeryfikacji;
}

void Wykladowca::setLicznikMaterialowDoWeryfikacji(int i) {
    licznikMaterialowDoWeryfikacji = i;
}

void Wykladowca::witaj() {

}

