//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wykladowca.h
//  @ Date : 16.05.2026
//  @ Author :
//
//


#if !defined(_WYKLADOWCA_H)
#define _WYKLADOWCA_H

#include "Konto.h"

class Wykladowca : public Konto {
public:
	bool zweryfikujSugestieStudenta();
	void dodajMaterial(string n, string t, string z);
	void dodajPrzedmiot(string nazwa, string opis, string kontakt);
	Wykladowca(string l, string h);
	~Wykladowca();
	bool getAktywnaWeryfikacja();
	void setAktywnaWeryfikacja(bool b);
private:
    bool aktywnaWeryfikacja;
};

#endif  //_WYKLADOWCA_H
