//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Admin.h
//  @ Date : 15.05.2026
//  @ Author :
//
//


#if !defined(_ADMIN_H)
#define _ADMIN_H

#include "Konto.h"
#include <string>

class Admin : public Konto {
public:
	void dodajMaterial(string tytul);
	Admin(string l, string h);
	~Admin();
};

#endif  //_ADMIN_H
