//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Admin.cpp
//  @ Date : 15.05.2026
//  @ Author :
//
//


#include "Admin.h"
#include "Material.h"
#include <iostream>

void Admin::dodajMaterial(string title) {
    cout << "Administrator " << getLogin() << " dodaje material zweryfikowany przez wykladowce o tytule: " << title << endl;
}

Admin::Admin(string login, string password) : Konto(login, password) {
    cout << "Utworzono konto administratora: " << getLogin() << endl;
}

Admin::~Admin() {
    cout << "Usunieto konto administratora: " << getLogin() << endl;
}

