//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.cpp
//  @ Date : 15.05.2026
//  @ Author :
//
//


#include "Student.h"
#include "Przedmiot.h"
#include "Material.h"
#include <iostream>

void Student::pozyskajMaterial(string subject, string title, string group) {
    // Aktualizujemy grupê studenta na tê podan¹ w parametrze (g)
    this->grupa = group;

    cout << "Student " << getLogin() << " (Grupa: " << group << ") pozyskuje nastêpuj¹cy materia³: " << endl;
    cout << " Przedmiot: " << subject << endl;
    cout << " Tytul materialu: " << title << endl;
}

bool Student::zaproponujMaterial(string data) {
    cout << "Student " << getLogin() << " zglasza sugestie: " << data << endl;

    return true;
}

Student::Student(string login, string password, string group): Konto(login, password), grupa(group) {
    cout << "Utworzono konto studenta: " << getLogin() << " z grupy " << group << endl;
}

Student::~Student() {
    cout << "Usunieto konto studenta: " << getLogin() << " z grupy " << group << endl;
}

