//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wykladowca.cpp
//  @ Date : 15.05.2026
//  @ Author :
//
//

#include "Wykladowca.h"
#include "Przedmiot.h" // Do³¹czamy nag³ówek Przedmiotu
#include "Material.h"  // Do³¹czamy nag³ówek Materia³u
#include <iostream>

bool Wykladowca::zweryfikujSugestieStudenta() {
    cout << "Wykladowca " << getLogin() << " weryfikuje sugestie." << endl;
    bool ifAccepted = true;
}

void Wykladowca::dodajMaterial(string subject, string title, string link) {
    cout << "Wykladowca " << getLogin() << " tworzy nowy material: " << title << endl;

    Material* nowyMaterial = new Material(title, link);
    cout << "Material zosta³ dodany do przedmiotu o nazwie: " << subject << endl;
}

void Wykladowca::dodajPrzedmiot(string name, string desc, string contact) {
    cout << "Wykladowca " << getLogin() << " tworzy przedmiot: " << name << endl;

    Przedmiot* nowyPrzedmiot = new Przedmiot(name, desc, contact);
    nowyPrzedmiot->attachWykladowca(this);
}

Wykladowca::Wykladowca(string login, string password): Konto(login, password) {
    cout << "Utworzono konto wykladowcy: " << getLogin() << endl;
}

Wykladowca::~Wykladowca() {
    cout << "Usunieto konto wykladowcy: " << getLogin() << endl;
}

