//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Konto.cpp
//  @ Date : 20.04.2026
//  @ Author :
//
//


#include "Konto.h"

Konto::Konto(string lg, string h) {
    login = lg;
    haslo = h;
}

string Konto::getLogin() {
    return login;
}

void Konto::setLogin(string s) {
    login = s;
}

bool Konto::autentykacja(string h) {
    if (h == haslo){
        return true;
    }
    else {
        return false;
    }
}

Konto::~Konto() {

}

