//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Konto.h
//  @ Date : 20.04.2026
//  @ Author :
//
//


#if !defined(_KONTO_H)
#define _KONTO_H
#include <string>
#include <iostream>

using namespace std;


class Konto {
public:
	Konto(string lg, string h);
	string getLogin();
	void setLogin(string s);
	bool autentykacja(string h);
	~Konto();
private:
	string login;
	string haslo;
};

#endif  //_KONTO_H
