//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Sesja.cpp
//  @ Date : 20.04.2026
//  @ Author :
//
//


#include "Sesja.h"

Sesja::Sesja(string ipVal) {
    ip = ipVal;

    proby = 0;
    czyJestZablokowana = false;
    zablokowanaDo = 0;
    konto = nullptr;
}

string Sesja::getIp() {
    return ip;
}

int Sesja::getProby() {
    return proby;
}

bool Sesja::getCzyJestZablokowana() {
    return czyJestZablokowana;
}

time_t Sesja::getZablokowanaDo() {
    return zablokowanaDo;
}

void Sesja::setIp(string s) {
    ip = s;
}

void Sesja::setProby(int i) {
    proby = i;
}

void Sesja::setCzyJestZablokowana(bool b) {
    czyJestZablokowana = b;
}

void Sesja::setZablokowanaDo(time_t t) {
    zablokowanaDo = t;
}

Konto* Sesja::getKonto() {
    return konto;
}

void Sesja::setKonto(Konto* k) {
    konto = k;
}

Sesja::~Sesja(){
    cout << "Procesz zniszczenia sesji o ip " << ip << "\n";
}

