//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Sesja.h
//  @ Date : 20.04.2026
//  @ Author :
//
//


#if !defined(_SESJA_H)
#define _SESJA_H
#include <string>
#include <iostream>
#include "Konto.h"

using namespace std;


class Sesja {
public:
	Sesja(string ipVal);
	string getIp();
	int getProby();
	bool getCzyJestZablokowana();
	time_t getZablokowanaDo();
	void setIp(string s);
	void setProby(int i);
	void setCzyJestZablokowana(bool b);
	void setZablokowanaDo(time_t t);
	Konto* getKonto();
	void setKonto(Konto* k);
	~Sesja();
private:
	string ip;
	int proby;
	bool czyJestZablokowana;
	time_t zablokowanaDo;
	Konto* konto;
};

#endif  //_SESJA_H
