//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Website.h
//  @ Date : 20.04.2026
//  @ Author :
//
//


#if !defined(_WEBSITE_H)
#define _WEBSITE_H
#include <string>
#include <vector>
#include "Sesja.h"
#include "Konto.h"

using namespace std;


class Website {
public:
	vector<Sesja*> sesje;
	Website(string html);
	bool rejestracja(string lg, string h, string ip);
	bool logowanie(string lg, string h, string ip);
	void attachKonto(Konto* noweKonto);
	void detachKonto(string login);
	string getAdresHtml();
	void setAdresHtml(string s);
	void zablokujSesje(string ip);
	void attachSesja(Sesja* sesja);
	void detachSesja(string ip);
	Konto* getKonto(string login);
	Sesja* getSesja(string ip);
	~Website();
private:
	string adresHtml;
	vector<Konto*> konta;
};

#endif  //_WEBSITE_H
