//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Website.cpp
//  @ Date : 20.04.2026
//  @ Author :
//
//


#include "Website.h"

Website::Website(string html) {
    adresHtml = html;
}

bool Website::rejestracja(string lg, string h, string ip) {
    Sesja* aktualnaSesja = getSesja(ip);

    if (aktualnaSesja == nullptr){
        cout << "Nie znalieziono sesji o ip " << ip << ", proces logowania przerwano\n";
        return false;
    }

    Konto* foundKonto = nullptr;
    vector<Konto*>::iterator it;

    for (it = konta.begin(); it != konta.end(); it++){
        if ((*it)->getLogin() == lg){
            foundKonto = (*it);
            break;
        }
    }

    if (foundKonto != nullptr){
        cout << "Niestety uzytkownik o loginie " << lg << " juz istnieje w systemie, prosze wymyslec sobie inney login uzytkownika\n";
        return false;
    }

    string passwordCheck = "";
    cout << "Prosze podtwierdzic haslo:\n";
    cin >> passwordCheck;

    if (passwordCheck == h){
        cout << "Rejestracja udana, dodajemy uzytkownika o loginie " << lg << " do systemu...\n";
        attachKonto(new Konto(lg, h));
    }
    else {
        cout << "Podtwierdzone haslo niestety nie zgadza sie z poprzednim haslem, prosze sprobowac ponownie\n";
        cout << "Prosze teraz zalogowac sie do systemu\n";
        return true;
    }


}

bool Website::logowanie(string lg, string h, string ip) {
    Sesja* aktualnaSesja = getSesja(ip);

    if (aktualnaSesja == nullptr){
        cout << "Nie znalieziono sesji o ip " << ip << ", proces logowania przerwano\n";
        return false;
    }

    if (aktualnaSesja->getCzyJestZablokowana()) {
        time_t currentTime = time(nullptr);

        if (currentTime < aktualnaSesja->getZablokowanaDo()) {
            long long left = aktualnaSesja->getZablokowanaDo() - currentTime;
            cout << "Sesja zablokowana, " << left << " sekund kary\n";
            return false;
        }
        else {
            aktualnaSesja->setCzyJestZablokowana(false);
            aktualnaSesja->setProby(0);
            cout << "Blokada minela, mozesz sprobowac ponownie\n";
        }
    }

    Konto* foundKonto = nullptr;
    vector<Konto*>::iterator it;

    for (it = konta.begin(); it != konta.end(); it++){
        if ((*it)->getLogin() == lg){
            foundKonto = (*it);
            break;
        }
    }

    if (foundKonto == nullptr){
        cout << "Nie znaleziono uzytkownika o loginie " << lg << ", czy chcesz zarajestrowac uzytkownika o takim loginie?\n";
        return false;
    }

    if (foundKonto->autentykacja(h)){
        cout << "Zalogowanie na strone " << adresHtml << " udalo sie\n";
        return true;
    }
    else {
            if (aktualnaSesja->getProby() >= 5){
                cout << "Przekroczony limit prob, musimy zablokowac sesje o ip " << aktualnaSesja->getIp() << " na 15 minut, prosze sprobowac pozniej\n";

                aktualnaSesja->setCzyJestZablokowana(true);
                aktualnaSesja->setZablokowanaDo(time(nullptr) + 15 * 60);
            }

            aktualnaSesja->setProby(aktualnaSesja->getProby() + 1);

            cout << "Niepoprawne haslo dla uzytkownika o loginie " << lg << ", sprobuje ponownie, zostalo " << 5 - aktualnaSesja->getProby() << " prob\n";

            return false;
    }
}

void Website::attachKonto(Konto* noweKonto) {
    konta.push_back(noweKonto);
}

void Website::detachKonto(string login) {
    vector<Konto*>::iterator it;

    for (it = konta.begin(); it != konta.end(); it++){
        if ((*it)->getLogin() == login){
            konta.erase(it);
        }
    }
}

string Website::getAdresHtml() {
    return adresHtml;
}

void Website::setAdresHtml(string s) {
    adresHtml = s;
}

void Website::zablokujSesje(string ip) {
    vector<Sesja*>::iterator it;

    for (it = sesje.begin(); it != sesje.end(); it++){
        if ((*it)->getIp() == ip){
            (*it)->setCzyJestZablokowana(true);
            (*it)->setZablokowanaDo(time(nullptr) + 15 * 60);
            break;
        }
    }
}

void Website::attachSesja(Sesja* sesja) {
    sesje.push_back(sesja);
}

void Website::detachSesja(string ip) {
       vector<Sesja*>::iterator it;

    for (it = sesje.begin(); it != sesje.end(); it++){
        if ((*it)->getIp() == ip){
            sesje.erase(it);

            break;
        }
    }
}

Konto* Website::getKonto(string login) {
    vector<Konto*>::iterator it;
    Konto* newKonto = nullptr;

    for (it = konta.begin(); it != konta.end(); it++){
        if ((*it)->getLogin() == login){
            newKonto = (*it);

            break;
        }
    }

    if (newKonto != nullptr){
        return newKonto;
    }
    else {
        cout << "Nie znaleziono konta o loginie " << login << "\n";
        return nullptr;
    }
}

Sesja* Website::getSesja(string ip) {
    vector<Sesja*>::iterator it;
    Sesja* newSesja = nullptr;

    for (it = sesje.begin(); it != sesje.end(); it++){
        if ((*it)->getIp() == ip){
            newSesja = (*it);

            break;
        }
    }

    if (newSesja != nullptr){
        return newSesja;
    }
    else {
        cout << "Nie znaleziono sesji o ip " << ip << "\n";
        return nullptr;
    }
}

Website::~Website() {
    cout << "Procesz znieszczenia strony internetowej " << adresHtml << "\n";
}

